/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import dbService.SarzaService;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import utils.Convert;


/**
 *
 * @author branko.scekic
 */
public class PregledIzvestajaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PregledRadnihNalogaFrame
     *
     * @param sarzaDb
     */
    public PregledIzvestajaFrame(SarzaService sarzaDb) {
        initComponents();

        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

        this.sarzaDb = sarzaDb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        brRadnohNaloga = new javax.swing.JLabel();
        MarkaBetona = new javax.swing.JLabel();
        Kupac = new javax.swing.JLabel();
        Gradiliste = new javax.swing.JLabel();
        DatumOd = new javax.swing.JLabel();
        DatumDo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIzvestaj = new javax.swing.JTable();
        jButtonPregledRNOdustani = new javax.swing.JButton();
        izvestaj = new javax.swing.JButton();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Izvestaj o potrosnji");

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));

        jLabel53.setText("Broj RN:");

        jLabel66.setText("Marka betona:");

        jLabel67.setText("Kupac:");

        jLabel68.setText("Gradilište:");

        jLabel71.setText("Datum od:");

        jLabel72.setText("Datum do:");

        brRadnohNaloga.setText("-");

        MarkaBetona.setText("-");

        Kupac.setText("-");

        Gradiliste.setText("-");

        DatumOd.setText("-");

        DatumDo.setText("-");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brRadnohNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MarkaBetona, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Kupac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gradiliste, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DatumDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(DatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kupac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brRadnohNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(MarkaBetona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Gradiliste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jTableIzvestaj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "br", "radni nalog", "0_4", "4_8", "8_16", "16_32", "cement", "filer", "aditiv 1", "aditiv 2", "voda", "izdato m3", "ime betona"
            }
        ));
        jTableIzvestaj.setFocusable(false);
        jScrollPane2.setViewportView(jTableIzvestaj);

        jButtonPregledRNOdustani.setText("Odustani");
        jButtonPregledRNOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledRNOdustaniActionPerformed(evt);
            }
        });

        izvestaj.setText("Izvestaj");
        izvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvestajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPregledRNOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPregledRNOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPregledRNOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledRNOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPregledRNOdustaniActionPerformed

    private void izvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvestajActionPerformed
       setPodaciZaglavlje();
       printReport(jTableIzvestaj);
    }//GEN-LAST:event_izvestajActionPerformed

     private void printReport(JTable jTable) {
        try {
            DefaultTableModel de = (DefaultTableModel) jTable.getModel();
            JasperReport jr = JasperCompileManager.compileReport("C:\\NetVision\\reports\\Report1.jrxml");
            //JasperReport jr = JasperCompileManager.compileReport("D:\\Programiranje\\netVisionValjevo\\src\\reports\\Report1.jrxml");

            
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(jr, podaci, new JRTableModelDataSource(de));
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException ex) {
            Logger.getLogger(PregledIzvestajaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setPodaciZaglavlje(){
        podaci = new HashMap();
        podaci.put("rn", "");
        podaci.put("markaBetona", "");
        podaci.put("kupac", "");
        podaci.put("gradiliste", "");
        podaci.put("datumOd", "");
        podaci.put("datumDo", "");
        
        
        if (brRadnohNaloga.getText().length() != 0) {
            podaci.put("rn", brRadnohNaloga.getText());
        }
        if (MarkaBetona.getText().length() != 0) {
            podaci.put("markaBetona", MarkaBetona.getText());
        }
        if (Kupac.getText().length() != 0) {
            podaci.put("kupac", Kupac.getText());
        }
        
        if (Gradiliste.getText().length() != 0) {
            podaci.put("gradiliste", Gradiliste.getText());
        }

        if (DatumOd.getText().length() != 0) {
            podaci.put("datumOd", DatumOd.getText());
        }

       if (DatumDo.getText().length() != 0) {
            podaci.put("datumDo", DatumDo.getText());
        }
        
    }
    
    public void setFilters(String rn, String markaBetona, String kupac, String gradiliste, String datumOd, String datumDo){
        brRadnohNaloga.setText(rn);
        MarkaBetona.setText(markaBetona);
        Kupac.setText(kupac);
        Gradiliste.setText(gradiliste);
        DatumOd.setText(datumOd);
        DatumDo.setText(datumDo);
    }
    
    public void getData(JTable table) {
       fillTableIzvestaj(table);
       
    }

    // videti kod starih app za cement i komponente
    private void fillTableIzvestaj(JTable table) {

        ukupnoAgregat04 = 0;
        ukupnoAgregat48 = 0;
        ukupnoAgregat816 = 0;
        ukupnoAgregat1632 = 0;
        ukupnoCement = 0;
        ukupnoFiler = 0;
        ukupnoAditiv1 = 0;
        ukupnoAditiv2 = 0;
        ukupnoVoda = 0;
        ukupnoBetona = 0;

        int brRow = table.getRowCount();
        
        Object[][] obj = new Object[brRow+1][13];
        for (int j = 0; j < brRow; j++) {
            getRowsukupno(obj, j, table);
        }
        
        obj[brRow][0] = brRow + 1;
        obj[brRow][1] = "ukupno";
        obj[brRow][2] = ukupnoAgregat04;
        obj[brRow][3] = ukupnoAgregat48;
        obj[brRow][4] = ukupnoAgregat816;
        obj[brRow][5] = ukupnoAgregat1632;
        obj[brRow][6] = ukupnoCement;
        obj[brRow][7] = ukupnoFiler;
        obj[brRow][8] = Convert.getRounFloat(ukupnoAditiv1, 2);
        obj[brRow][9] = Convert.getRounFloat(ukupnoAditiv2, 2);
        obj[brRow][10] = ukupnoVoda;
        obj[brRow][11] = Convert.round2Decimal(ukupnoBetona);
        obj[brRow][12] = "";
       
       

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b", "rn", "0_4 izd", "4_8 izd", "8_16 izd", "16_32 izd", "cement", "filer", "aditiv 1", "aditiv 2", "voda", "izdato m3","ime betona"});
        jTableIzvestaj.setModel(model);
        jTableIzvestaj.setRowMargin(4);
        jTableIzvestaj.setRowHeight(40);
        jTableIzvestaj.setShowGrid(true);
        jTableIzvestaj.getColumnModel().getColumn(0).setMaxWidth(45);
        jTableIzvestaj.setDefaultEditor(Object.class, null);
        
        

    }

    private void getRowsukupno(Object[][] obj, int j, JTable table) {
        List<db.Sarza> result;

        long ukupnoRn = 0l;
        int ukupnoAgregatizdato04 = 0;
        int ukupnoAgregatizdato48 = 0;
        int ukupnoAgregatizdato816 = 0;
        int ukupnoAgregatizdato1632 = 0;
        int ukupnoCementizdato = 0;
        int ukupnoFilerizdato = 0;
        float ukupnoAditiv1izdato = 0;
        float ukupnoAditiv2izdato = 0;
        int ukupnoVodaIzdata = 0;
        float ukupnoBetonaIzdato = 0;
        String imeBetona =""; 

        //int i = 0;
        result = sarzaDb.getSarzeZaRadniNalog(Long.parseLong(table.getValueAt(j, 1).toString()));

        for (db.Sarza auto : result) {
            ukupnoRn = auto.getRadninalog().getRn();
            ukupnoAgregatizdato04 = ukupnoAgregatizdato04 + auto.getAgregatizdato04();
            ukupnoAgregatizdato48 = ukupnoAgregatizdato48 + auto.getAgregaizdato48();
            ukupnoAgregatizdato816 = ukupnoAgregatizdato816 + auto.getAgregatizdato816();
            ukupnoAgregatizdato1632 = ukupnoAgregatizdato1632 + auto.getAgregatizdato1632();
            ukupnoCementizdato = ukupnoCementizdato + auto.getCementizdato();
            ukupnoFilerizdato = ukupnoFilerizdato + auto.getFilerizdato();
            ukupnoAditiv1izdato = ukupnoAditiv1izdato + auto.getAditiv1izdato();
            ukupnoAditiv2izdato = ukupnoAditiv2izdato + auto.getAditiv2izdato();
            ukupnoVodaIzdata = (int) (ukupnoVodaIzdata + auto.getVodaizdato());
            ukupnoBetonaIzdato = auto.getRadninalog().getIsporucenom3();
            imeBetona = auto.getRadninalog().getMarkabetona();
        }
        
        ukupnoAgregat04 = ukupnoAgregat04 + ukupnoAgregatizdato04;
        ukupnoAgregat48 = ukupnoAgregat48 + ukupnoAgregatizdato48;
        ukupnoAgregat816 = ukupnoAgregat816 + ukupnoAgregatizdato816;
        ukupnoAgregat1632 = ukupnoAgregat1632+ ukupnoAgregatizdato1632;
        ukupnoCement = ukupnoCement + ukupnoCementizdato;
        ukupnoFiler = ukupnoFiler + ukupnoFilerizdato;
        ukupnoAditiv1 = ukupnoAditiv1 + ukupnoAditiv1izdato;
        ukupnoAditiv2 = ukupnoAditiv2 + ukupnoAditiv2izdato;
        ukupnoVoda = ukupnoVoda + ukupnoVodaIzdata;
        ukupnoBetona = ukupnoBetona + ukupnoBetonaIzdato;

        obj[j][0] = j + 1;
        obj[j][1] = ukupnoRn;
        obj[j][2] = ukupnoAgregatizdato04;
        obj[j][3] = ukupnoAgregatizdato48;
        obj[j][4] = ukupnoAgregatizdato816;
        obj[j][5] = ukupnoAgregatizdato1632;
        obj[j][6] = ukupnoCementizdato;
        obj[j][7] = ukupnoFilerizdato;
        obj[j][8] = Convert.getRounFloat(ukupnoAditiv1izdato, 2);
        obj[j][9] = Convert.getRounFloat(ukupnoAditiv2izdato, 2);
        obj[j][10] = ukupnoVodaIzdata;
        obj[j][11] = Convert.round2Decimal(ukupnoBetonaIzdato);
        obj[j][12] = imeBetona;
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatumDo;
    private javax.swing.JLabel DatumOd;
    private javax.swing.JLabel Gradiliste;
    private javax.swing.JLabel Kupac;
    private javax.swing.JLabel MarkaBetona;
    private javax.swing.JLabel brRadnohNaloga;
    private javax.swing.JButton izvestaj;
    private javax.swing.JButton jButtonPregledRNOdustani;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIzvestaj;
    // End of variables declaration//GEN-END:variables
    private final SarzaService sarzaDb;

    private int ukupnoAgregat04 = 0;
    private int ukupnoAgregat48 = 0;
    private int ukupnoAgregat816 = 0;
    private int ukupnoAgregat1632 = 0;
    private int ukupnoCement = 0;
    private int ukupnoFiler = 0;
    private float ukupnoAditiv1 = 0;
    private float ukupnoAditiv2 = 0;
    private int ukupnoVoda = 0;
    private float ukupnoBetona;
    
    private Map<String, Object> podaci;
}
