/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.form;

import dbService.RucniRadService;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.net.URL;
import javax.persistence.EntityManagerFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import netvisionNew.win.AktivniRadniNaloziFrame;
import netvisionNew.win.GradilisteFrame;
import netvisionNew.win.KupacFrame;
import netvisionNew.win.MarkaBetonaFrame;
import netvisionNew.win.NoviRadniNalogFrame;
import netvisionNew.win.PregledRadnihNalogaFrame;
import netvisionNew.win.PregledRucniRadFrame;
import netvisionNew.win.VozacFrame;
import netvisionNew.win.VoziloFrame;

/**
 *
 * @author branko.scekic
 */
public class DataForm extends javax.swing.JFrame {

    /**
     * Creates new form DataForm
     * @param emf
     * @param kupacFrame
     * @param gradilisteFrame
     * @param vozacFrame
     * @param voziloFrame
     * @param markaBetonaFrame
     * @param aktivniRadniNaloziFrame
     * @param noviRadniNalogFrame
     * @param pregledRadnihNalogaFrame
     */
    public DataForm(EntityManagerFactory emf, VozacFrame vozacFrame, KupacFrame kupacFrame, 
            GradilisteFrame gradilisteFrame, VoziloFrame voziloFrame, MarkaBetonaFrame markaBetonaFrame,
            AktivniRadniNaloziFrame aktivniRadniNaloziFrame, NoviRadniNalogFrame noviRadniNalogFrame,
            PregledRadnihNalogaFrame pregledRadnihNalogaFrame, RucniRadService rucniRadDb) {
        initComponents();
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.vozacFrame = vozacFrame;
        this.kupacFrame = kupacFrame;
        this.gradilisteFrame = gradilisteFrame;
        this.voziloFrame = voziloFrame;
        this.markaBetonaFrame = markaBetonaFrame;
        this.aktivniRadniNaloziFrame = aktivniRadniNaloziFrame;
        this.noviRadniNalogFrame = noviRadniNalogFrame;
        this.pregledRadnihNalogaFrame = pregledRadnihNalogaFrame;
        this.rucniRadDb = rucniRadDb;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVozac = new javax.swing.JButton();
        jButtonKupac = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonVozilo = new javax.swing.JButton();
        jButtonMarkaetona = new javax.swing.JButton();
        jButtonAktivniRN = new javax.swing.JButton();
        jButtonNoviRadniNalog = new javax.swing.JButton();
        jButtonSviRadniNalozi = new javax.swing.JButton();
        jButtonRucniRad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jButtonVozac.setText("Vozači");
        jButtonVozac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVozacActionPerformed(evt);
            }
        });

        jButtonKupac.setText("Kupac");
        jButtonKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKupacActionPerformed(evt);
            }
        });

        jButton1.setText("Gradilište");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonVozilo.setText("Vozilo");
        jButtonVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoziloActionPerformed(evt);
            }
        });

        jButtonMarkaetona.setText("Marka Betona");
        jButtonMarkaetona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkaetonaActionPerformed(evt);
            }
        });

        jButtonAktivniRN.setText("Aktivni radni nalozi");
        jButtonAktivniRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAktivniRNActionPerformed(evt);
            }
        });

        jButtonNoviRadniNalog.setText("Novi radni nalog");
        jButtonNoviRadniNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviRadniNalogActionPerformed(evt);
            }
        });

        jButtonSviRadniNalozi.setText("Svi Radni Nalozi");
        jButtonSviRadniNalozi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSviRadniNaloziActionPerformed(evt);
            }
        });

        jButtonRucniRad.setText("Izvestaj o rucnom radu");
        jButtonRucniRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRucniRadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonRucniRad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSviRadniNalozi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jButtonVozac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButtonKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jButtonMarkaetona)
                                .addGap(53, 53, 53)
                                .addComponent(jButtonNoviRadniNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAktivniRN)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVozac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMarkaetona, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKupac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNoviRadniNalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAktivniRN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSviRadniNalozi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRucniRad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVozacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVozacActionPerformed
        vozacFrame.setVisible(true);
        vozacFrame.getVozaci();
    }//GEN-LAST:event_jButtonVozacActionPerformed

    private void jButtonKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKupacActionPerformed
        kupacFrame.setVisible(true);
        kupacFrame.getKupci();
    }//GEN-LAST:event_jButtonKupacActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gradilisteFrame.setVisible(true);
        gradilisteFrame.getGradiliste();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoziloActionPerformed
        voziloFrame.setVisible(true);
        voziloFrame.getVozila();
    }//GEN-LAST:event_jButtonVoziloActionPerformed

    private void jButtonMarkaetonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkaetonaActionPerformed
        markaBetonaFrame.setVisible(true);
        markaBetonaFrame.getRecepti();
        markaBetonaFrame.clear();
    }//GEN-LAST:event_jButtonMarkaetonaActionPerformed

    private void jButtonAktivniRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAktivniRNActionPerformed
        aktivniRadniNaloziFrame.setVisible(true);
        aktivniRadniNaloziFrame.getAktivniRN();
    }//GEN-LAST:event_jButtonAktivniRNActionPerformed

    private void jButtonNoviRadniNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviRadniNalogActionPerformed
        noviRadniNalogFrame.setVisible(true);
        noviRadniNalogFrame.getDataForNewRN();
    }//GEN-LAST:event_jButtonNoviRadniNalogActionPerformed

    private void jButtonSviRadniNaloziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSviRadniNaloziActionPerformed
        pregledRadnihNalogaFrame.setVisible(true);
        pregledRadnihNalogaFrame.getSviRN();
    }//GEN-LAST:event_jButtonSviRadniNaloziActionPerformed

    private void jButtonRucniRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRucniRadActionPerformed
        this.pregledRucniRadFrame = new PregledRucniRadFrame(rucniRadDb);
        pregledRucniRadFrame.setVisible(true);
    }//GEN-LAST:event_jButtonRucniRadActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void showOnScreen(int screen, JFrame frame) {
        //za prikaz na displeju kod multidispleja
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gd = ge.getScreenDevices();
        if (screen > -1 && screen < gd.length) {
            frame.setLocation(gd[screen].getDefaultConfiguration().getBounds().x, frame.getY());
        } else if (gd.length > 0) {
            frame.setLocation(gd[0].getDefaultConfiguration().getBounds().x, frame.getY());
        } else {
            throw new RuntimeException("No Screens Found");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAktivniRN;
    private javax.swing.JButton jButtonKupac;
    private javax.swing.JButton jButtonMarkaetona;
    private javax.swing.JButton jButtonNoviRadniNalog;
    private javax.swing.JButton jButtonRucniRad;
    private javax.swing.JButton jButtonSviRadniNalozi;
    private javax.swing.JButton jButtonVozac;
    private javax.swing.JButton jButtonVozilo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private final VozacFrame vozacFrame;
    private final KupacFrame kupacFrame;
    private final GradilisteFrame gradilisteFrame;
    private final VoziloFrame voziloFrame;
    private final MarkaBetonaFrame markaBetonaFrame;
    private final AktivniRadniNaloziFrame aktivniRadniNaloziFrame;
    private final NoviRadniNalogFrame noviRadniNalogFrame;
    private final PregledRadnihNalogaFrame pregledRadnihNalogaFrame;
    private PregledRucniRadFrame pregledRucniRadFrame;
    private final RucniRadService rucniRadDb;
}
