/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import dbService.MarkaBetonaService;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class MarkaBetonaFrame extends javax.swing.JFrame {

    private long id;
    /**
     * Creates new form RecepturaFrame
     * @param markaBetonaDb
     * @param vodaPlusMinus
     */
    public MarkaBetonaFrame(MarkaBetonaService markaBetonaDb) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.markaBetonaDb = markaBetonaDb;
        this.id=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        receptBr1 = new javax.swing.JButton();
        receptBr2 = new javax.swing.JButton();
        receptBr3 = new javax.swing.JButton();
        receptBr4 = new javax.swing.JButton();
        receptBr5 = new javax.swing.JButton();
        receptBr6 = new javax.swing.JButton();
        receptBr7 = new javax.swing.JButton();
        receptBr8 = new javax.swing.JButton();
        receptBr9 = new javax.swing.JButton();
        receptBr10 = new javax.swing.JButton();
        receptBr11 = new javax.swing.JButton();
        receptBr12 = new javax.swing.JButton();
        receptBr13 = new javax.swing.JButton();
        receptBr14 = new javax.swing.JButton();
        receptBr15 = new javax.swing.JButton();
        receptBr16 = new javax.swing.JButton();
        receptBr17 = new javax.swing.JButton();
        receptBr18 = new javax.swing.JButton();
        receptBr19 = new javax.swing.JButton();
        receptBr20 = new javax.swing.JButton();
        receptBr21 = new javax.swing.JButton();
        receptBr22 = new javax.swing.JButton();
        receptBr23 = new javax.swing.JButton();
        receptBr24 = new javax.swing.JButton();
        receptBr25 = new javax.swing.JButton();
        receptBr26 = new javax.swing.JButton();
        receptBr27 = new javax.swing.JButton();
        receptBr28 = new javax.swing.JButton();
        receptBr29 = new javax.swing.JButton();
        receptBr30 = new javax.swing.JButton();
        receptBr31 = new javax.swing.JButton();
        receptBr32 = new javax.swing.JButton();
        receptBr33 = new javax.swing.JButton();
        receptBr34 = new javax.swing.JButton();
        receptBr35 = new javax.swing.JButton();
        receptBr36 = new javax.swing.JButton();
        receptBr37 = new javax.swing.JButton();
        receptBr38 = new javax.swing.JButton();
        receptBr39 = new javax.swing.JButton();
        receptBr40 = new javax.swing.JButton();
        receptBr41 = new javax.swing.JButton();
        receptBr42 = new javax.swing.JButton();
        receptBr43 = new javax.swing.JButton();
        receptBr44 = new javax.swing.JButton();
        receptBr45 = new javax.swing.JButton();
        receptBr46 = new javax.swing.JButton();
        receptBr47 = new javax.swing.JButton();
        receptBr48 = new javax.swing.JButton();
        receptBr49 = new javax.swing.JButton();
        receptBr50 = new javax.swing.JButton();
        nazivIzabranogRecepta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jButtonReceptiOtkljucaj = new javax.swing.JButton();
        jButtonReceptiOdustani = new javax.swing.JButton();
        RecepturaZadavanjeFrakcija0_4 = new javax.swing.JTextField();
        RecepturaZadavanjeFrakcija4_8 = new javax.swing.JTextField();
        RecepturaZadavanjeFrakcija8_16 = new javax.swing.JTextField();
        RecepturaZadavanjeFrakcija16_32 = new javax.swing.JTextField();
        jButtonRecepturaSacuvaj = new javax.swing.JButton();
        RecepturaZadavanjeCement = new javax.swing.JTextField();
        RecepturaZadavanjeFiler = new javax.swing.JTextField();
        RecepturaZadavanjeAditivA1 = new javax.swing.JTextField();
        RecepturaZadavanjeAditivA2 = new javax.swing.JTextField();
        RecepturaZadavanjeVoda = new javax.swing.JTextField();
        RecepturaVremeMesanja = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        RecepturaVremePraznjenja = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel15.setLayout(null);

        receptBr1.setBackground(new java.awt.Color(204, 204, 204));
        receptBr1.setText("rec1");
        receptBr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr1ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr1);
        receptBr1.setBounds(50, 80, 150, 40);

        receptBr2.setBackground(new java.awt.Color(204, 204, 204));
        receptBr2.setText("rec2");
        receptBr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr2ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr2);
        receptBr2.setBounds(220, 80, 150, 40);

        receptBr3.setBackground(new java.awt.Color(204, 204, 204));
        receptBr3.setText("rec3");
        receptBr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr3ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr3);
        receptBr3.setBounds(390, 80, 150, 40);

        receptBr4.setBackground(new java.awt.Color(204, 204, 204));
        receptBr4.setText("rec4");
        receptBr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr4ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr4);
        receptBr4.setBounds(560, 80, 150, 40);

        receptBr5.setBackground(new java.awt.Color(204, 204, 204));
        receptBr5.setText("rec5");
        receptBr5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr5ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr5);
        receptBr5.setBounds(50, 130, 150, 40);

        receptBr6.setBackground(new java.awt.Color(204, 204, 204));
        receptBr6.setText("rec6");
        receptBr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr6ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr6);
        receptBr6.setBounds(220, 130, 150, 40);

        receptBr7.setBackground(new java.awt.Color(204, 204, 204));
        receptBr7.setText("rec7");
        receptBr7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr7ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr7);
        receptBr7.setBounds(390, 130, 150, 40);

        receptBr8.setBackground(new java.awt.Color(204, 204, 204));
        receptBr8.setText("rec8");
        receptBr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr8ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr8);
        receptBr8.setBounds(560, 130, 150, 40);

        receptBr9.setBackground(new java.awt.Color(204, 204, 204));
        receptBr9.setText("rec9");
        receptBr9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr9ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr9);
        receptBr9.setBounds(50, 180, 150, 40);

        receptBr10.setBackground(new java.awt.Color(204, 204, 204));
        receptBr10.setText("rec10");
        receptBr10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr10ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr10);
        receptBr10.setBounds(220, 180, 150, 40);

        receptBr11.setBackground(new java.awt.Color(204, 204, 204));
        receptBr11.setText("rec11");
        receptBr11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr11ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr11);
        receptBr11.setBounds(390, 180, 150, 40);

        receptBr12.setBackground(new java.awt.Color(204, 204, 204));
        receptBr12.setText("rec12");
        receptBr12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr12ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr12);
        receptBr12.setBounds(560, 180, 150, 40);

        receptBr13.setBackground(new java.awt.Color(204, 204, 204));
        receptBr13.setText("rec13");
        receptBr13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr13ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr13);
        receptBr13.setBounds(50, 230, 150, 40);

        receptBr14.setBackground(new java.awt.Color(204, 204, 204));
        receptBr14.setText("rec14");
        receptBr14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr14ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr14);
        receptBr14.setBounds(220, 230, 150, 40);

        receptBr15.setBackground(new java.awt.Color(204, 204, 204));
        receptBr15.setText("rec15");
        receptBr15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr15ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr15);
        receptBr15.setBounds(390, 230, 150, 40);

        receptBr16.setBackground(new java.awt.Color(204, 204, 204));
        receptBr16.setText("rec16");
        receptBr16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr16ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr16);
        receptBr16.setBounds(560, 230, 150, 40);

        receptBr17.setBackground(new java.awt.Color(204, 204, 204));
        receptBr17.setText("rec17");
        receptBr17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr17ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr17);
        receptBr17.setBounds(50, 280, 150, 40);

        receptBr18.setBackground(new java.awt.Color(204, 204, 204));
        receptBr18.setText("rec18");
        receptBr18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr18ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr18);
        receptBr18.setBounds(220, 280, 150, 40);

        receptBr19.setBackground(new java.awt.Color(204, 204, 204));
        receptBr19.setText("rec19");
        receptBr19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr19ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr19);
        receptBr19.setBounds(390, 280, 150, 40);

        receptBr20.setBackground(new java.awt.Color(204, 204, 204));
        receptBr20.setText("rec20");
        receptBr20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr20ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr20);
        receptBr20.setBounds(560, 280, 150, 40);

        receptBr21.setBackground(new java.awt.Color(204, 204, 204));
        receptBr21.setText("rec21");
        receptBr21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr21ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr21);
        receptBr21.setBounds(50, 330, 150, 40);

        receptBr22.setBackground(new java.awt.Color(204, 204, 204));
        receptBr22.setText("rec22");
        receptBr22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr22ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr22);
        receptBr22.setBounds(220, 330, 150, 40);

        receptBr23.setBackground(new java.awt.Color(204, 204, 204));
        receptBr23.setText("rec23");
        receptBr23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr23ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr23);
        receptBr23.setBounds(390, 330, 150, 40);

        receptBr24.setBackground(new java.awt.Color(204, 204, 204));
        receptBr24.setText("rec24");
        receptBr24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr24ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr24);
        receptBr24.setBounds(560, 330, 150, 40);

        receptBr25.setBackground(new java.awt.Color(204, 204, 204));
        receptBr25.setText("rec25");
        receptBr25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr25ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr25);
        receptBr25.setBounds(50, 380, 150, 40);

        receptBr26.setBackground(new java.awt.Color(204, 204, 204));
        receptBr26.setText("rec26");
        receptBr26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr26ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr26);
        receptBr26.setBounds(220, 380, 150, 40);

        receptBr27.setBackground(new java.awt.Color(204, 204, 204));
        receptBr27.setText("rec27");
        receptBr27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr27ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr27);
        receptBr27.setBounds(390, 380, 150, 40);

        receptBr28.setBackground(new java.awt.Color(204, 204, 204));
        receptBr28.setText("rec28");
        receptBr28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr28ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr28);
        receptBr28.setBounds(560, 380, 150, 40);

        receptBr29.setBackground(new java.awt.Color(204, 204, 204));
        receptBr29.setText("rec29");
        receptBr29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr29ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr29);
        receptBr29.setBounds(50, 430, 150, 40);

        receptBr30.setBackground(new java.awt.Color(204, 204, 204));
        receptBr30.setText("rec30");
        receptBr30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr30ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr30);
        receptBr30.setBounds(220, 430, 150, 40);

        receptBr31.setBackground(new java.awt.Color(204, 204, 204));
        receptBr31.setText("rec31");
        receptBr31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr31ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr31);
        receptBr31.setBounds(390, 430, 150, 40);

        receptBr32.setBackground(new java.awt.Color(204, 204, 204));
        receptBr32.setText("rec32");
        receptBr32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr32ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr32);
        receptBr32.setBounds(560, 430, 150, 40);

        receptBr33.setBackground(new java.awt.Color(204, 204, 204));
        receptBr33.setText("rec33");
        receptBr33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr33ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr33);
        receptBr33.setBounds(50, 480, 150, 40);

        receptBr34.setBackground(new java.awt.Color(204, 204, 204));
        receptBr34.setText("rec34");
        receptBr34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr34ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr34);
        receptBr34.setBounds(220, 480, 150, 40);

        receptBr35.setBackground(new java.awt.Color(204, 204, 204));
        receptBr35.setText("rec35");
        receptBr35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr35ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr35);
        receptBr35.setBounds(390, 480, 150, 40);

        receptBr36.setBackground(new java.awt.Color(204, 204, 204));
        receptBr36.setText("rec36");
        receptBr36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr36ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr36);
        receptBr36.setBounds(560, 480, 150, 40);

        receptBr37.setBackground(new java.awt.Color(204, 204, 204));
        receptBr37.setText("rec37");
        receptBr37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr37ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr37);
        receptBr37.setBounds(50, 530, 150, 40);

        receptBr38.setBackground(new java.awt.Color(204, 204, 204));
        receptBr38.setText("rec38");
        receptBr38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr38ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr38);
        receptBr38.setBounds(220, 530, 150, 40);

        receptBr39.setBackground(new java.awt.Color(204, 204, 204));
        receptBr39.setText("rec39");
        receptBr39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr39ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr39);
        receptBr39.setBounds(390, 530, 150, 40);

        receptBr40.setBackground(new java.awt.Color(204, 204, 204));
        receptBr40.setText("rec40");
        receptBr40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr40ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr40);
        receptBr40.setBounds(560, 530, 150, 40);

        receptBr41.setBackground(new java.awt.Color(204, 204, 204));
        receptBr41.setText("rec41");
        receptBr41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr41ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr41);
        receptBr41.setBounds(50, 580, 150, 40);

        receptBr42.setBackground(new java.awt.Color(204, 204, 204));
        receptBr42.setText("rec42");
        receptBr42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr42ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr42);
        receptBr42.setBounds(220, 580, 150, 40);

        receptBr43.setBackground(new java.awt.Color(204, 204, 204));
        receptBr43.setText("rec43");
        receptBr43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr43ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr43);
        receptBr43.setBounds(390, 580, 150, 40);

        receptBr44.setBackground(new java.awt.Color(204, 204, 204));
        receptBr44.setText("rec44");
        receptBr44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr44ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr44);
        receptBr44.setBounds(560, 580, 150, 40);

        receptBr45.setBackground(new java.awt.Color(204, 204, 204));
        receptBr45.setText("rec45");
        receptBr45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr45ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr45);
        receptBr45.setBounds(50, 630, 150, 40);

        receptBr46.setBackground(new java.awt.Color(204, 204, 204));
        receptBr46.setText("rec46");
        receptBr46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr46ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr46);
        receptBr46.setBounds(220, 630, 150, 40);

        receptBr47.setBackground(new java.awt.Color(204, 204, 204));
        receptBr47.setText("rec47");
        receptBr47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr47ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr47);
        receptBr47.setBounds(390, 630, 150, 40);

        receptBr48.setBackground(new java.awt.Color(204, 204, 204));
        receptBr48.setText("rec48");
        receptBr48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr48ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr48);
        receptBr48.setBounds(560, 630, 150, 40);

        receptBr49.setBackground(new java.awt.Color(204, 204, 204));
        receptBr49.setText("rec49");
        receptBr49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr49ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr49);
        receptBr49.setBounds(50, 680, 150, 40);

        receptBr50.setBackground(new java.awt.Color(204, 204, 204));
        receptBr50.setText("rec50");
        receptBr50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptBr50ActionPerformed(evt);
            }
        });
        jPanel15.add(receptBr50);
        receptBr50.setBounds(220, 680, 150, 40);

        nazivIzabranogRecepta.setText("recept");
        nazivIzabranogRecepta.setEnabled(false);
        jPanel15.add(nazivIzabranogRecepta);
        nazivIzabranogRecepta.setBounds(850, 20, 200, 28);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("2. Frakcija 4_8 mm");
        jPanel15.add(jLabel1);
        jLabel1.setBounds(730, 150, 120, 20);

        jLabel34.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Spisak receptura");
        jPanel15.add(jLabel34);
        jLabel34.setBounds(50, 20, 540, 30);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Izabrana receptura");
        jLabel36.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jPanel15.add(jLabel36);
        jLabel36.setBounds(640, 20, 180, 30);

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("(sve količine se zadaju za 1 m3 betona)");
        jPanel15.add(jLabel37);
        jLabel37.setBounds(830, 50, 230, 20);

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("3. Frakcija 8_16 mm");
        jPanel15.add(jLabel38);
        jLabel38.setBounds(730, 190, 120, 20);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("4. Frakcija 16_32 mm");
        jPanel15.add(jLabel46);
        jLabel46.setBounds(730, 230, 120, 20);

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("5. Cement");
        jPanel15.add(jLabel47);
        jLabel47.setBounds(730, 270, 120, 20);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("1. Frakcija 0_4 mm");
        jPanel15.add(jLabel48);
        jLabel48.setBounds(730, 110, 120, 20);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText("6. Filer");
        jPanel15.add(jLabel49);
        jLabel49.setBounds(730, 310, 120, 20);

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel50.setText("7. Aditiv A1");
        jPanel15.add(jLabel50);
        jLabel50.setBounds(730, 350, 120, 20);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("8. Aditiv A2");
        jPanel15.add(jLabel51);
        jLabel51.setBounds(730, 390, 120, 20);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("9. Voda");
        jPanel15.add(jLabel52);
        jLabel52.setBounds(730, 430, 120, 20);

        jButtonReceptiOtkljucaj.setText("Otključaj");
        jButtonReceptiOtkljucaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceptiOtkljucajActionPerformed(evt);
            }
        });
        jPanel15.add(jButtonReceptiOtkljucaj);
        jButtonReceptiOtkljucaj.setBounds(730, 620, 340, 50);

        jButtonReceptiOdustani.setText("Odustani");
        jButtonReceptiOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceptiOdustaniActionPerformed(evt);
            }
        });
        jPanel15.add(jButtonReceptiOdustani);
        jButtonReceptiOdustani.setBounds(920, 690, 150, 60);

        RecepturaZadavanjeFrakcija0_4.setText("0");
        RecepturaZadavanjeFrakcija0_4.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeFrakcija0_4);
        RecepturaZadavanjeFrakcija0_4.setBounds(860, 100, 90, 30);

        RecepturaZadavanjeFrakcija4_8.setText("0");
        RecepturaZadavanjeFrakcija4_8.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeFrakcija4_8);
        RecepturaZadavanjeFrakcija4_8.setBounds(860, 140, 90, 30);

        RecepturaZadavanjeFrakcija8_16.setText("0");
        RecepturaZadavanjeFrakcija8_16.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeFrakcija8_16);
        RecepturaZadavanjeFrakcija8_16.setBounds(860, 180, 90, 30);

        RecepturaZadavanjeFrakcija16_32.setText("0");
        RecepturaZadavanjeFrakcija16_32.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeFrakcija16_32);
        RecepturaZadavanjeFrakcija16_32.setBounds(860, 220, 90, 30);

        jButtonRecepturaSacuvaj.setText("Sačuvaj");
        jButtonRecepturaSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecepturaSacuvajActionPerformed(evt);
            }
        });
        jPanel15.add(jButtonRecepturaSacuvaj);
        jButtonRecepturaSacuvaj.setBounds(730, 690, 140, 60);

        RecepturaZadavanjeCement.setText("0");
        RecepturaZadavanjeCement.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeCement);
        RecepturaZadavanjeCement.setBounds(860, 260, 90, 30);

        RecepturaZadavanjeFiler.setText("0");
        RecepturaZadavanjeFiler.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeFiler);
        RecepturaZadavanjeFiler.setBounds(860, 300, 90, 30);

        RecepturaZadavanjeAditivA1.setText("0");
        RecepturaZadavanjeAditivA1.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeAditivA1);
        RecepturaZadavanjeAditivA1.setBounds(860, 340, 90, 30);

        RecepturaZadavanjeAditivA2.setText("0");
        RecepturaZadavanjeAditivA2.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeAditivA2);
        RecepturaZadavanjeAditivA2.setBounds(860, 380, 90, 30);

        RecepturaZadavanjeVoda.setText("0");
        RecepturaZadavanjeVoda.setEnabled(false);
        jPanel15.add(RecepturaZadavanjeVoda);
        RecepturaZadavanjeVoda.setBounds(860, 420, 90, 30);

        RecepturaVremeMesanja.setText("0");
        RecepturaVremeMesanja.setEnabled(false);
        jPanel15.add(RecepturaVremeMesanja);
        RecepturaVremeMesanja.setBounds(880, 470, 90, 30);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel54.setText("11. Vreme pražnjenja (sec)");
        jPanel15.add(jLabel54);
        jLabel54.setBounds(730, 510, 160, 20);

        RecepturaVremePraznjenja.setText("0");
        RecepturaVremePraznjenja.setEnabled(false);
        jPanel15.add(RecepturaVremePraznjenja);
        RecepturaVremePraznjenja.setBounds(880, 500, 90, 30);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("10. Vreme mešanja (sec)");
        jPanel15.add(jLabel53);
        jLabel53.setBounds(730, 480, 160, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background.jpg"))); // NOI18N
        jPanel15.add(jLabel3);
        jLabel3.setBounds(0, 0, 1084, 755);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void receptBr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr1ActionPerformed
        id = 1;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr1ActionPerformed

    private void receptBr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr2ActionPerformed
        id = 2;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr2ActionPerformed

    private void receptBr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr3ActionPerformed
        id=3;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr3ActionPerformed

    private void receptBr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr4ActionPerformed
        id=4;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr4ActionPerformed

    private void receptBr5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr5ActionPerformed
        id=5;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr5ActionPerformed

    private void receptBr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr6ActionPerformed
        id=6;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr6ActionPerformed

    private void receptBr7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr7ActionPerformed
        id=7;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr7ActionPerformed

    private void receptBr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr8ActionPerformed
        id=8;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr8ActionPerformed

    private void receptBr9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr9ActionPerformed
        id=9;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr9ActionPerformed

    private void receptBr10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr10ActionPerformed
        id=10;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr10ActionPerformed

    private void receptBr11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr11ActionPerformed
        id=11;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr11ActionPerformed

    private void receptBr12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr12ActionPerformed
        id=12;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr12ActionPerformed

    private void receptBr13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr13ActionPerformed
        id=13;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr13ActionPerformed

    private void receptBr14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr14ActionPerformed
        id=14;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr14ActionPerformed

    private void receptBr15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr15ActionPerformed
        id=15;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr15ActionPerformed

    private void receptBr16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr16ActionPerformed
        id=16;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr16ActionPerformed

    private void receptBr17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr17ActionPerformed
        id=17;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr17ActionPerformed

    private void receptBr18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr18ActionPerformed
        id=18;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr18ActionPerformed

    private void receptBr19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr19ActionPerformed
        id=19;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr19ActionPerformed

    private void receptBr20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr20ActionPerformed
        id=20;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr20ActionPerformed

    private void receptBr21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr21ActionPerformed
        id=21;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr21ActionPerformed

    private void receptBr22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr22ActionPerformed
        id=22;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr22ActionPerformed

    private void receptBr23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr23ActionPerformed
        id=23;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr23ActionPerformed

    private void receptBr24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr24ActionPerformed
        id=24;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr24ActionPerformed

    private void receptBr25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr25ActionPerformed
        id=25;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr25ActionPerformed

    private void receptBr26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr26ActionPerformed
        id=26;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr26ActionPerformed

    private void receptBr27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr27ActionPerformed
        id=27;
        fillFields(markaBetonaDb.getRecept(id));

    }//GEN-LAST:event_receptBr27ActionPerformed

    private void receptBr28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr28ActionPerformed
        id=28;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr28ActionPerformed

    private void receptBr29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr29ActionPerformed
        id=29;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr29ActionPerformed

    private void receptBr30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr30ActionPerformed
        id=30;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr30ActionPerformed

    private void receptBr31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr31ActionPerformed
        id=31;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr31ActionPerformed

    private void receptBr32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr32ActionPerformed
        id=32;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr32ActionPerformed

    private void receptBr33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr33ActionPerformed
        id=33;
        fillFields(markaBetonaDb.getRecept(id));

    }//GEN-LAST:event_receptBr33ActionPerformed

    private void receptBr34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr34ActionPerformed
        id=34;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr34ActionPerformed

    private void receptBr35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr35ActionPerformed
        id=35;
        fillFields(markaBetonaDb.getRecept(id));

    }//GEN-LAST:event_receptBr35ActionPerformed

    private void receptBr36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr36ActionPerformed
        id=36;
        fillFields(markaBetonaDb.getRecept(id));

    }//GEN-LAST:event_receptBr36ActionPerformed

    private void receptBr37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr37ActionPerformed
        id=37;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr37ActionPerformed

    private void receptBr38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr38ActionPerformed
        id=38;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr38ActionPerformed

    private void receptBr39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr39ActionPerformed
        id=39;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr39ActionPerformed

    private void receptBr40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr40ActionPerformed
        id=40;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr40ActionPerformed

    private void receptBr41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr41ActionPerformed
        id=41;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr41ActionPerformed

    private void receptBr42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr42ActionPerformed
        id=42;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr42ActionPerformed

    private void receptBr43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr43ActionPerformed
        id=43;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr43ActionPerformed

    private void receptBr44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr44ActionPerformed
        id=44;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr44ActionPerformed

    private void receptBr45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr45ActionPerformed
        id=45;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr45ActionPerformed

    private void receptBr46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr46ActionPerformed
        id=46;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr46ActionPerformed

    private void receptBr47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr47ActionPerformed
        id=47;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr47ActionPerformed

    private void receptBr48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr48ActionPerformed
        id=48;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr48ActionPerformed

    private void receptBr49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr49ActionPerformed
        id=49;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr49ActionPerformed

    private void receptBr50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptBr50ActionPerformed
        id=50;
        fillFields(markaBetonaDb.getRecept(id));
    }//GEN-LAST:event_receptBr50ActionPerformed

    private void jButtonReceptiOtkljucajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceptiOtkljucajActionPerformed
        nazivIzabranogRecepta.setEnabled(true);
        RecepturaZadavanjeFrakcija0_4.setEnabled(true);
        RecepturaZadavanjeFrakcija4_8.setEnabled(true);
        RecepturaZadavanjeFrakcija8_16.setEnabled(true);
        RecepturaZadavanjeFrakcija16_32.setEnabled(true);
        RecepturaZadavanjeCement.setEnabled(true);
        RecepturaZadavanjeFiler.setEnabled(true);
        RecepturaZadavanjeAditivA1.setEnabled(true);
        RecepturaZadavanjeAditivA2.setEnabled(true);
        RecepturaZadavanjeVoda.setEnabled(true);
        RecepturaVremeMesanja.setEnabled(true);
        RecepturaVremePraznjenja.setEnabled(true);
       
    }//GEN-LAST:event_jButtonReceptiOtkljucajActionPerformed

    private void jButtonReceptiOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceptiOdustaniActionPerformed
        this.setVisible(false);
        disableRecepture();
    }//GEN-LAST:event_jButtonReceptiOdustaniActionPerformed

    private void jButtonRecepturaSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecepturaSacuvajActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            markaBetonaDb.setRecept(id, nazivIzabranogRecepta.getText(), Double.parseDouble(RecepturaZadavanjeFrakcija0_4.getText()), 
                    Double.parseDouble(RecepturaZadavanjeFrakcija4_8.getText()), Double.parseDouble(RecepturaZadavanjeFrakcija8_16.getText()),
                    Double.parseDouble(RecepturaZadavanjeFrakcija16_32.getText()), Double.parseDouble(RecepturaZadavanjeCement.getText()),
                    Double.parseDouble(RecepturaZadavanjeFiler.getText()), Double.parseDouble(RecepturaZadavanjeAditivA1.getText()),
                    Double.parseDouble(RecepturaZadavanjeAditivA2.getText()), Double.parseDouble(RecepturaZadavanjeVoda.getText()),
                    Double.parseDouble(RecepturaVremeMesanja.getText()), Double.parseDouble(RecepturaVremePraznjenja.getText()));
            
        }
        disableRecepture();
    }//GEN-LAST:event_jButtonRecepturaSacuvajActionPerformed

    public void disableRecepture(){
        nazivIzabranogRecepta.setEnabled(false);
        RecepturaZadavanjeFrakcija0_4.setEnabled(false);
        RecepturaZadavanjeFrakcija4_8.setEnabled(false);
        RecepturaZadavanjeFrakcija8_16.setEnabled(false);
        RecepturaZadavanjeFrakcija16_32.setEnabled(false);
        RecepturaZadavanjeCement.setEnabled(false);
        RecepturaZadavanjeFiler.setEnabled(false);
        RecepturaZadavanjeAditivA1.setEnabled(false);
        RecepturaZadavanjeAditivA2.setEnabled(false);
        RecepturaZadavanjeVoda.setEnabled(false);
        RecepturaVremeMesanja.setEnabled(false);
        RecepturaVremePraznjenja.setEnabled(false);
        
    }
    
    public void getRecepti(){
        updateResult(markaBetonaDb.getRecepti());
    }
    
    private void updateResult(List<db.Markabetona> result){
        //nazivIzabranogRecepta.setText(result.get((int)(id-1)).getMarkabeton());
        receptBr1.setText(result.get(0).getMarkabeton());
        receptBr2.setText(result.get(1).getMarkabeton());
        receptBr3.setText(result.get(2).getMarkabeton());
        receptBr4.setText(result.get(3).getMarkabeton());
        receptBr5.setText(result.get(4).getMarkabeton());
        receptBr6.setText(result.get(5).getMarkabeton());
        receptBr7.setText(result.get(6).getMarkabeton());
        receptBr8.setText(result.get(7).getMarkabeton());
        receptBr9.setText(result.get(8).getMarkabeton());
        receptBr10.setText(result.get(9).getMarkabeton());
        receptBr11.setText(result.get(10).getMarkabeton());
        receptBr12.setText(result.get(11).getMarkabeton());
        receptBr13.setText(result.get(12).getMarkabeton());
        receptBr14.setText(result.get(13).getMarkabeton());
        receptBr15.setText(result.get(14).getMarkabeton());
        receptBr16.setText(result.get(15).getMarkabeton());
        receptBr17.setText(result.get(16).getMarkabeton());
        receptBr18.setText(result.get(17).getMarkabeton());
        receptBr19.setText(result.get(18).getMarkabeton());
        receptBr20.setText(result.get(19).getMarkabeton());
        receptBr21.setText(result.get(20).getMarkabeton());
        receptBr22.setText(result.get(21).getMarkabeton());
        receptBr23.setText(result.get(22).getMarkabeton());
        receptBr24.setText(result.get(23).getMarkabeton());
        receptBr25.setText(result.get(24).getMarkabeton());
        receptBr26.setText(result.get(25).getMarkabeton());
        receptBr27.setText(result.get(26).getMarkabeton());
        receptBr28.setText(result.get(27).getMarkabeton());
        receptBr29.setText(result.get(28).getMarkabeton());
        receptBr30.setText(result.get(29).getMarkabeton());
        receptBr31.setText(result.get(30).getMarkabeton());
        receptBr32.setText(result.get(31).getMarkabeton());
        receptBr33.setText(result.get(32).getMarkabeton());
        receptBr34.setText(result.get(33).getMarkabeton());
        receptBr35.setText(result.get(34).getMarkabeton());
        receptBr36.setText(result.get(35).getMarkabeton());
        receptBr37.setText(result.get(36).getMarkabeton());
        receptBr38.setText(result.get(37).getMarkabeton());
        receptBr39.setText(result.get(38).getMarkabeton());
        receptBr40.setText(result.get(39).getMarkabeton());
        receptBr41.setText(result.get(40).getMarkabeton());
        receptBr42.setText(result.get(41).getMarkabeton());
        receptBr43.setText(result.get(42).getMarkabeton());
        receptBr44.setText(result.get(43).getMarkabeton());
        receptBr45.setText(result.get(44).getMarkabeton());
        receptBr46.setText(result.get(45).getMarkabeton());
        receptBr47.setText(result.get(46).getMarkabeton());
        receptBr48.setText(result.get(47).getMarkabeton());
        receptBr49.setText(result.get(48).getMarkabeton());
        receptBr50.setText(result.get(49).getMarkabeton());
    }
    
    private void fillFields(db.Markabetona result){
        nazivIzabranogRecepta.setText(result.getMarkabeton());
        RecepturaZadavanjeFrakcija0_4.setText(Convert.doubleToString(result.getFrakcija04()));
        RecepturaZadavanjeFrakcija4_8.setText(Convert.doubleToString(result.getFrakcija48()));
        RecepturaZadavanjeFrakcija8_16.setText(Convert.doubleToString(result.getFrakcija816()));
        RecepturaZadavanjeFrakcija16_32.setText(Convert.doubleToString(result.getFrakcija1632()));
        RecepturaZadavanjeCement.setText(Convert.doubleToString(result.getCement()));
        RecepturaZadavanjeFiler.setText(Convert.doubleToString(result.getFiler()));
        RecepturaZadavanjeAditivA1.setText(Double.toString(result.getAditiv1()));
        RecepturaZadavanjeAditivA2.setText(Double.toString(result.getAditiv2()));
        RecepturaZadavanjeVoda.setText(Convert.doubleToString(result.getVoda()));
        RecepturaVremeMesanja.setText(Convert.doubleToString(result.getVrememesanja()));
        RecepturaVremePraznjenja.setText(Convert.doubleToString(result.getVremepraznjenja()));
        
    }
    
    public void clear(){
        nazivIzabranogRecepta.setText("");
        RecepturaZadavanjeFrakcija0_4.setText("");
        RecepturaZadavanjeFrakcija4_8.setText("");
        RecepturaZadavanjeFrakcija8_16.setText("");
        RecepturaZadavanjeFrakcija16_32.setText("");
        RecepturaZadavanjeCement.setText("");
        RecepturaZadavanjeFiler.setText("");
        RecepturaZadavanjeAditivA1.setText("");
        RecepturaZadavanjeAditivA2.setText("");
        RecepturaZadavanjeVoda.setText("");
        RecepturaVremeMesanja.setText("");
        RecepturaVremePraznjenja.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RecepturaVremeMesanja;
    private javax.swing.JTextField RecepturaVremePraznjenja;
    private javax.swing.JTextField RecepturaZadavanjeAditivA1;
    private javax.swing.JTextField RecepturaZadavanjeAditivA2;
    private javax.swing.JTextField RecepturaZadavanjeCement;
    private javax.swing.JTextField RecepturaZadavanjeFiler;
    private javax.swing.JTextField RecepturaZadavanjeFrakcija0_4;
    private javax.swing.JTextField RecepturaZadavanjeFrakcija16_32;
    private javax.swing.JTextField RecepturaZadavanjeFrakcija4_8;
    private javax.swing.JTextField RecepturaZadavanjeFrakcija8_16;
    private javax.swing.JTextField RecepturaZadavanjeVoda;
    private javax.swing.JButton jButtonReceptiOdustani;
    private javax.swing.JButton jButtonReceptiOtkljucaj;
    private javax.swing.JButton jButtonRecepturaSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JTextField nazivIzabranogRecepta;
    private javax.swing.JButton receptBr1;
    private javax.swing.JButton receptBr10;
    private javax.swing.JButton receptBr11;
    private javax.swing.JButton receptBr12;
    private javax.swing.JButton receptBr13;
    private javax.swing.JButton receptBr14;
    private javax.swing.JButton receptBr15;
    private javax.swing.JButton receptBr16;
    private javax.swing.JButton receptBr17;
    private javax.swing.JButton receptBr18;
    private javax.swing.JButton receptBr19;
    private javax.swing.JButton receptBr2;
    private javax.swing.JButton receptBr20;
    private javax.swing.JButton receptBr21;
    private javax.swing.JButton receptBr22;
    private javax.swing.JButton receptBr23;
    private javax.swing.JButton receptBr24;
    private javax.swing.JButton receptBr25;
    private javax.swing.JButton receptBr26;
    private javax.swing.JButton receptBr27;
    private javax.swing.JButton receptBr28;
    private javax.swing.JButton receptBr29;
    private javax.swing.JButton receptBr3;
    private javax.swing.JButton receptBr30;
    private javax.swing.JButton receptBr31;
    private javax.swing.JButton receptBr32;
    private javax.swing.JButton receptBr33;
    private javax.swing.JButton receptBr34;
    private javax.swing.JButton receptBr35;
    private javax.swing.JButton receptBr36;
    private javax.swing.JButton receptBr37;
    private javax.swing.JButton receptBr38;
    private javax.swing.JButton receptBr39;
    private javax.swing.JButton receptBr4;
    private javax.swing.JButton receptBr40;
    private javax.swing.JButton receptBr41;
    private javax.swing.JButton receptBr42;
    private javax.swing.JButton receptBr43;
    private javax.swing.JButton receptBr44;
    private javax.swing.JButton receptBr45;
    private javax.swing.JButton receptBr46;
    private javax.swing.JButton receptBr47;
    private javax.swing.JButton receptBr48;
    private javax.swing.JButton receptBr49;
    private javax.swing.JButton receptBr5;
    private javax.swing.JButton receptBr50;
    private javax.swing.JButton receptBr6;
    private javax.swing.JButton receptBr7;
    private javax.swing.JButton receptBr8;
    private javax.swing.JButton receptBr9;
    // End of variables declaration//GEN-END:variables

    private final MarkaBetonaService markaBetonaDb;

    public JButton getReceptBr1() {
        return receptBr1;
    }

    public JButton getReceptBr10() {
        return receptBr10;
    }

    public JButton getReceptBr11() {
        return receptBr11;
    }

    public JButton getReceptBr12() {
        return receptBr12;
    }

    public JButton getReceptBr13() {
        return receptBr13;
    }

    public JButton getReceptBr14() {
        return receptBr14;
    }

    public JButton getReceptBr15() {
        return receptBr15;
    }

    public JButton getReceptBr16() {
        return receptBr16;
    }

    public JButton getReceptBr17() {
        return receptBr17;
    }

    public JButton getReceptBr18() {
        return receptBr18;
    }

    public JButton getReceptBr19() {
        return receptBr19;
    }

    public JButton getReceptBr2() {
        return receptBr2;
    }

    public JButton getReceptBr20() {
        return receptBr20;
    }

    public JButton getReceptBr21() {
        return receptBr21;
    }

    public JButton getReceptBr22() {
        return receptBr22;
    }

    public JButton getReceptBr23() {
        return receptBr23;
    }

    public JButton getReceptBr24() {
        return receptBr24;
    }

    public JButton getReceptBr25() {
        return receptBr25;
    }

    public JButton getReceptBr26() {
        return receptBr26;
    }

    public JButton getReceptBr27() {
        return receptBr27;
    }

    public JButton getReceptBr28() {
        return receptBr28;
    }

    public JButton getReceptBr29() {
        return receptBr29;
    }

    public JButton getReceptBr3() {
        return receptBr3;
    }

    public JButton getReceptBr30() {
        return receptBr30;
    }

    public JButton getReceptBr31() {
        return receptBr31;
    }

    public JButton getReceptBr32() {
        return receptBr32;
    }

    public JButton getReceptBr33() {
        return receptBr33;
    }

    public JButton getReceptBr34() {
        return receptBr34;
    }

    public JButton getReceptBr35() {
        return receptBr35;
    }

    public JButton getReceptBr36() {
        return receptBr36;
    }

    public JButton getReceptBr37() {
        return receptBr37;
    }

    public JButton getReceptBr38() {
        return receptBr38;
    }

    public JButton getReceptBr39() {
        return receptBr39;
    }

    public JButton getReceptBr4() {
        return receptBr4;
    }

    public JButton getReceptBr40() {
        return receptBr40;
    }

    public JButton getReceptBr41() {
        return receptBr41;
    }

    public JButton getReceptBr42() {
        return receptBr42;
    }

    public JButton getReceptBr43() {
        return receptBr43;
    }

    public JButton getReceptBr44() {
        return receptBr44;
    }

    public JButton getReceptBr45() {
        return receptBr45;
    }

    public JButton getReceptBr46() {
        return receptBr46;
    }

    public JButton getReceptBr47() {
        return receptBr47;
    }

    public JButton getReceptBr48() {
        return receptBr48;
    }

    public JButton getReceptBr49() {
        return receptBr49;
    }

    public JButton getReceptBr5() {
        return receptBr5;
    }

    public JButton getReceptBr50() {
        return receptBr50;
    }

    public JButton getReceptBr6() {
        return receptBr6;
    }

    public JButton getReceptBr7() {
        return receptBr7;
    }

    public JButton getReceptBr8() {
        return receptBr8;
    }

    public JButton getReceptBr9() {
        return receptBr9;
    }

    public JTextField getRecepturaZadavanjeAditivA1() {
        return RecepturaZadavanjeAditivA1;
    }

    public JTextField getRecepturaZadavanjeAditivA2() {
        return RecepturaZadavanjeAditivA2;
    }

    public JTextField getRecepturaZadavanjeCement() {
        return RecepturaZadavanjeCement;
    }

    public JTextField getRecepturaZadavanjeFiler() {
        return RecepturaZadavanjeFiler;
    }

    public JTextField getRecepturaZadavanjeFrakcija0_4() {
        return RecepturaZadavanjeFrakcija0_4;
    }

    public JTextField getRecepturaZadavanjeFrakcija16_32() {
        return RecepturaZadavanjeFrakcija16_32;
    }

    public JTextField getRecepturaZadavanjeFrakcija4_8() {
        return RecepturaZadavanjeFrakcija4_8;
    }

    public JTextField getRecepturaZadavanjeFrakcija8_16() {
        return RecepturaZadavanjeFrakcija8_16;
    }

    public JTextField getRecepturaZadavanjeVoda() {
        return RecepturaZadavanjeVoda;
    }

    public JTextField getNazivIzabranogRecepta() {
        return nazivIzabranogRecepta;
    }
}
