/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import betonMesalica.TekuciRN;
import dbService.GradilisteService;
import dbService.KupacService;
import dbService.MarkaBetonaService;
import dbService.RadniNalogService;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author branko.scekic
 */
public class NoviRadniNalogFrame extends javax.swing.JFrame {

    /**
     * Creates new form NoviRadniNalogFrame
     *
     * @param radniNalogDb
     * @param kupacDb
     * @param gradilisteDb
     * @param markaBetonaDb
     * @param kupacFrame
     * @param gradilisteFrame
     * @param novaOtpremaFrame
     * @param tekuciRN
     */
    public NoviRadniNalogFrame(RadniNalogService radniNalogDb, KupacService kupacDb, GradilisteService gradilisteDb,
            MarkaBetonaService markaBetonaDb, KupacFrame kupacFrame, GradilisteFrame gradilisteFrame, NovaOtpremaFrame novaOtpremaFrame,
            TekuciRN tekuciRN) {
        initComponents();

        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

        this.radniNalogDb = radniNalogDb;
        this.kupacDb = kupacDb;
        this.gradilisteDb = gradilisteDb;
        this.markaBetonaDb = markaBetonaDb;
        this.kupacFrame = kupacFrame;
        this.gradilisteFrame = gradilisteFrame;
        this.novaOtpremaFrame = novaOtpremaFrame;
        this.tekuciRN = tekuciRN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButtonNoviRadniNalogPotvrdi = new javax.swing.JButton();
        jButtonNoviRadniNalogOdustani = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        brojRadnogNaloga = new javax.swing.JTextField();
        selektovanaMarkaBetona = new javax.swing.JComboBox<>();
        selektovanKupac = new javax.swing.JComboBox<>();
        PregledKupaca = new javax.swing.JButton();
        selektovanGradiliste = new javax.swing.JComboBox<>();
        PregledGradilista = new javax.swing.JButton();
        zadataKolicinaRadniNalog = new javax.swing.JSpinner();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Kreiranje novog radnog naloga");

        jLabel33.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Količina:");

        jButtonNoviRadniNalogPotvrdi.setText("Potvrdi");
        jButtonNoviRadniNalogPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviRadniNalogPotvrdiActionPerformed(evt);
            }
        });

        jButtonNoviRadniNalogOdustani.setText("Odustani");
        jButtonNoviRadniNalogOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviRadniNalogOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNoviRadniNalogPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jButtonNoviRadniNalogOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNoviRadniNalogPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonNoviRadniNalogOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Broj radnog naloga:");

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Kupac:");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Gradilište:");

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Marka betona: ");

        brojRadnogNaloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brojRadnogNalogaActionPerformed(evt);
            }
        });

        selektovanaMarkaBetona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rec 1" }));

        selektovanKupac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kupac" }));

        PregledKupaca.setText("+");
        PregledKupaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledKupacaActionPerformed(evt);
            }
        });

        selektovanGradiliste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gradiliste" }));

        PregledGradilista.setText("+");
        PregledGradilista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledGradilistaActionPerformed(evt);
            }
        });

        zadataKolicinaRadniNalog.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10000.0d, 0.1d));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(brojRadnogNaloga)
                            .addComponent(selektovanaMarkaBetona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selektovanKupac, 0, 186, Short.MAX_VALUE)
                            .addComponent(selektovanGradiliste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zadataKolicinaRadniNalog))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PregledKupaca, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(PregledGradilista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brojRadnogNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selektovanKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PregledKupaca))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selektovanGradiliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PregledGradilista))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selektovanaMarkaBetona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zadataKolicinaRadniNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoviRadniNalogPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviRadniNalogPotvrdiActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da kreirate novi radni nalog?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            radniNalogDb.addRadniNalog(Long.parseLong(brojRadnogNaloga.getText()), selektovanKupac.getSelectedItem().toString(),
                    selektovanGradiliste.getSelectedItem().toString(), selektovanaMarkaBetona.getSelectedItem().toString(),
                    Float.parseFloat(zadataKolicinaRadniNalog.getValue().toString()));
            this.setVisible(false);
            getNewOtpremaFromRN();
        }


    }//GEN-LAST:event_jButtonNoviRadniNalogPotvrdiActionPerformed

    private void jButtonNoviRadniNalogOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviRadniNalogOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNoviRadniNalogOdustaniActionPerformed

    private void brojRadnogNalogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brojRadnogNalogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brojRadnogNalogaActionPerformed

    private void PregledKupacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledKupacaActionPerformed
        kupacFrame.setVisible(true);
        kupacFrame.getKupci();
        //this.setVisible(false);
    }//GEN-LAST:event_PregledKupacaActionPerformed

    private void PregledGradilistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledGradilistaActionPerformed
        gradilisteFrame.setVisible(true);
        gradilisteFrame.getGradiliste();
        //this.setVisible(false);
    }//GEN-LAST:event_PregledGradilistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PregledGradilista;
    private javax.swing.JButton PregledKupaca;
    private javax.swing.JTextField brojRadnogNaloga;
    private javax.swing.JButton jButtonNoviRadniNalogOdustani;
    private javax.swing.JButton jButtonNoviRadniNalogPotvrdi;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> selektovanGradiliste;
    private javax.swing.JComboBox<String> selektovanKupac;
    private javax.swing.JComboBox<String> selektovanaMarkaBetona;
    private javax.swing.JSpinner zadataKolicinaRadniNalog;
    // End of variables declaration//GEN-END:variables

    private final RadniNalogService radniNalogDb;
    private final KupacService kupacDb;
    private final GradilisteService gradilisteDb;
    private final MarkaBetonaService markaBetonaDb;
    private final KupacFrame kupacFrame;
    private final GradilisteFrame gradilisteFrame;
    private final NovaOtpremaFrame novaOtpremaFrame;
    private final TekuciRN tekuciRN;

    private void getNewOtpremaFromRN() {
        novaOtpremaFrame.setVisible(true);
        tekuciRN.setTekuciRN(radniNalogDb.getRN(Long.parseLong(brojRadnogNaloga.getText())));
        novaOtpremaFrame.fillDataForRN();
        tekuciRN.setReadiTekuciRN(true);
    }

    public void getDataForNewRN() {
        getRNNumber();
        getKupci();
        getGradiliste();
        getMarkaetona();
    }

    private void getKupci() {
        List<db.Kupac> result = kupacDb.getKupci();

        DefaultComboBoxModel model = (DefaultComboBoxModel) selektovanKupac.getModel();

        // removing old data
        model.removeAllElements();

        for (int i = 0; i < result.size(); i++) {
            if (result.get(i).getAktivan()) {
                model.addElement(result.get(i).getKupac());
            }
        }

        // setting model with new data
        selektovanKupac.setModel(model);
    }

    private void getGradiliste() {
        List<db.Gradiliste> result = gradilisteDb.getGradiliste();

        DefaultComboBoxModel model = (DefaultComboBoxModel) selektovanGradiliste.getModel();

        // removing old data
        model.removeAllElements();

        for (int i = 0; i < result.size(); i++) {
            if (result.get(i).getAktivno()) {
                model.addElement(result.get(i).getGradiliste());
            }
        }
        // setting model with new data
        selektovanGradiliste.setModel(model);
    }

    private void getMarkaetona() {
        List<db.Markabetona> result = markaBetonaDb.getRecepti();

        DefaultComboBoxModel model = (DefaultComboBoxModel) selektovanaMarkaBetona.getModel();

        // removing old data
        model.removeAllElements();

        for (int i = 0; i < result.size(); i++) {
            model.addElement(result.get(i).getMarkabeton());
        }
        // setting model with new data
        selektovanaMarkaBetona.setModel(model);
    }

    private void getRNNumber() {
        Date localDate = new Date();
        SimpleDateFormat dt1 = new SimpleDateFormat("MMyyHHmm");
        brojRadnogNaloga.setText(dt1.format(localDate));
    }
}
