/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import dbService.RucniRadService;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import report.PregledIzvestajaFrame;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class PregledRucniRadFrame extends javax.swing.JFrame {

    /**
     * Creates new form PregledRadnihNalogaFrame
     */
    public PregledRucniRadFrame(RucniRadService rucniRadDb) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.rucniRadDb = rucniRadDb;
        getAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        filterDatumOd = new com.github.lgooddatepicker.components.DatePicker();
        filterDatumDo = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRucniRad = new javax.swing.JTable();
        jButtonPregledRNOdustani = new javax.swing.JButton();
        jButtonFilterIzlistajRadneNaloge = new javax.swing.JButton();
        izvestaj = new javax.swing.JButton();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Rucni rad");

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));

        jLabel71.setText("Datum od:");

        jLabel72.setText("Datum do:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(filterDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel72)
                        .addComponent(filterDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTableRucniRad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "br", "Opis", "Vrednost", "Datum"
            }
        ));
        jTableRucniRad.setFocusable(false);
        jScrollPane2.setViewportView(jTableRucniRad);

        jButtonPregledRNOdustani.setText("Odustani");
        jButtonPregledRNOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledRNOdustaniActionPerformed(evt);
            }
        });

        jButtonFilterIzlistajRadneNaloge.setText("Izlistaj rucni rad");
        jButtonFilterIzlistajRadneNaloge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterIzlistajRadneNalogeActionPerformed(evt);
            }
        });

        izvestaj.setText("Izvestaj");
        izvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvestajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPregledRNOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFilterIzlistajRadneNaloge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFilterIzlistajRadneNaloge, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPregledRNOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPregledRNOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledRNOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPregledRNOdustaniActionPerformed

    private void jButtonFilterIzlistajRadneNalogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterIzlistajRadneNalogeActionPerformed
                
        List<db.Rucnirad> result = rucniRadDb.getRucniRadWhere(filterDatumOd.getText(), filterDatumDo.getText());
        fillTableRN(result);
    }//GEN-LAST:event_jButtonFilterIzlistajRadneNalogeActionPerformed

    private void izvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvestajActionPerformed
        if (jTableRucniRad.getRowCount() >= 1) {
            setPodaciZaglavlje();
            printReport(jTableRucniRad);
            
        }else{
            JOptionPane.showMessageDialog(this, "Popunite filtere za zeljeni izvestaj", "Obavestenje",0);
        }
    }//GEN-LAST:event_izvestajActionPerformed
    
     private void printReport(JTable jTable) {
        try {
            DefaultTableModel de = (DefaultTableModel) jTable.getModel();
            JasperReport jr = JasperCompileManager.compileReport("C:\\NetVision\\reports\\ReportRucno.jrxml");
            //JasperReport jr = JasperCompileManager.compileReport("D:\\Programiranje\\netVisionValjevo\\src\\reports\\Report1.jrxml");

            JasperPrint jasperPrint = JasperFillManager.fillReport(jr, podaci, new JRTableModelDataSource(de));
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException ex) {
            Logger.getLogger(PregledIzvestajaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getAll(){
        List<db.Rucnirad> result = rucniRadDb.getRucniRad();
        fillTableRN(result);
    }
    
    
    private void fillTableRN(List<db.Rucnirad> result) {
        int i = 0;
        Object[][] obj = new Object[result.size()][10];
        for (db.Rucnirad auto : result) {
            obj[i][0] = i + 1;
            obj[i][1] = auto.getOpis();
            obj[i][2] = auto.getVrednost();
            obj[i][3] = Convert.convertDateToStringDate(auto.getDatum()) + " " + Convert.convertDateToStringTime(auto.getDatum());
            
            //obj[i][7] = Convert.round2Decimal(auto.getUgovorenom3() - auto.getIsporucenom3());
            //obj[i][10] = Convert.convertDateToStringTime(auto.getDatumvreme());
            i++;
        }

        jTableRucniRad.removeAll();
        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b", "Opis", "Vrednost", "Datum"});
        jTableRucniRad.setModel(model);
        jTableRucniRad.setRowMargin(4);
        jTableRucniRad.setRowHeight(40);
        jTableRucniRad.setShowGrid(true);
        jTableRucniRad.getColumnModel().getColumn(0).setMaxWidth(45);
        jTableRucniRad.getColumnModel().getColumn(1).setMinWidth(85);
        jTableRucniRad.setDefaultEditor(Object.class, null);

    }
    
    private void setPodaciZaglavlje(){
        /*
        podaci = new HashMap();
        podaci.put("datumOd", "");
        podaci.put("datumDo", "");
        
        
        if (filterDatumOd.getText().length() != 0) {
            podaci.put("datumOd", filterDatumOd.getText());
        }

       if (filterDatumDo.getText().length() != 0) {
            podaci.put("datumDo", filterDatumOd.getText());
        }
        */
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker filterDatumDo;
    private com.github.lgooddatepicker.components.DatePicker filterDatumOd;
    private javax.swing.JButton izvestaj;
    private javax.swing.JButton jButtonFilterIzlistajRadneNaloge;
    private javax.swing.JButton jButtonPregledRNOdustani;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRucniRad;
    // End of variables declaration//GEN-END:variables
    private Map<String, Object> podaci;
    private final RucniRadService rucniRadDb;
}