/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import dbService.RadniNalogService;
import java.net.URL;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import report.PregledIzvestajaFrame;
import utils.Convert;
import utils.StatusRN;

/**
 *
 * @author branko.scekic
 */
public class PregledRadnihNalogaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PregledRadnihNalogaFrame
     * @param radniNalogDb
     * @param pregledRadnogNalogaPoOtpremamaFrame
     */
    public PregledRadnihNalogaFrame(RadniNalogService radniNalogDb, PregledOtpremaZaRadniNalogFrame pregledRadnogNalogaPoOtpremamaFrame, PregledIzvestajaFrame pregledIzvestajaFrame) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.radniNalogDb = radniNalogDb;
        this.pregledRadnogNalogaPoOtpremamaFrame = pregledRadnogNalogaPoOtpremamaFrame;
        this.pregledIzvestajaFrame = pregledIzvestajaFrame;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        filterRadniNalog = new javax.swing.JComboBox<>();
        jLabel66 = new javax.swing.JLabel();
        filterMarkaBetona = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        filterKupac = new javax.swing.JComboBox<>();
        jLabel68 = new javax.swing.JLabel();
        filterGradiliste = new javax.swing.JComboBox<>();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        filterStatus = new javax.swing.JComboBox<>();
        filterDatumOd = new com.github.lgooddatepicker.components.DatePicker();
        filterDatumDo = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRadniNalozi = new javax.swing.JTable();
        jButtonPregledRNOdustani = new javax.swing.JButton();
        jButtonFilterIzlistajRadneNaloge = new javax.swing.JButton();
        pregledRNDetalji = new javax.swing.JButton();
        izvestaj = new javax.swing.JButton();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Pregled radnih naloga");
        jLabel31.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));

        jLabel53.setText("Broj RN:");

        jLabel66.setText("Marka betona:");

        filterMarkaBetona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel67.setText("Kupac:");

        filterKupac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel68.setText("Gradilište:");

        filterGradiliste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel71.setText("Datum od:");

        jLabel72.setText("Datum do:");

        jLabel73.setText("Status:");

        filterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "svi", "aktivni", "zavrseni", "prekinuti" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterMarkaBetona, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterRadniNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filterGradiliste, 0, 200, Short.MAX_VALUE)
                    .addComponent(filterKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(filterDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel71)
                        .addComponent(jLabel73)
                        .addComponent(filterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filterDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(filterKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel68)
                            .addComponent(filterGradiliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(filterRadniNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel66)
                            .addComponent(filterMarkaBetona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTableRadniNalozi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "br", "radni nalog", "marka betona", "kupac", "gradiliste", "ugovoreno", "isporuceno", "preostalo", "datum", "status"
            }
        ));
        jTableRadniNalozi.setFocusable(false);
        jScrollPane2.setViewportView(jTableRadniNalozi);

        jButtonPregledRNOdustani.setText("Odustani");
        jButtonPregledRNOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledRNOdustaniActionPerformed(evt);
            }
        });

        jButtonFilterIzlistajRadneNaloge.setText("Izlistaj radne naloge");
        jButtonFilterIzlistajRadneNaloge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterIzlistajRadneNalogeActionPerformed(evt);
            }
        });

        pregledRNDetalji.setText("Detalji");
        pregledRNDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledRNDetaljiActionPerformed(evt);
            }
        });

        izvestaj.setText("Izvestaj");
        izvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvestajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(pregledRNDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPregledRNOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFilterIzlistajRadneNaloge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFilterIzlistajRadneNaloge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPregledRNOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregledRNDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPregledRNOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledRNOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPregledRNOdustaniActionPerformed

    private void jButtonFilterIzlistajRadneNalogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterIzlistajRadneNalogeActionPerformed
        
        fillTableRN(radniNalogDb.getFilteredData(filterRadniNalog.getSelectedItem().toString(), filterStatus.getSelectedIndex(),  
                filterKupac.getSelectedItem().toString(), filterGradiliste.getSelectedItem().toString(), filterMarkaBetona.getSelectedItem().toString(),
                filterDatumOd.getText(), filterDatumDo.getText()));
        
        pregledIzvestajaFrame.setFilters(filterRadniNalog.getSelectedItem().toString(), filterMarkaBetona.getSelectedItem().toString(), 
                    filterKupac.getSelectedItem().toString(), filterGradiliste.getSelectedItem().toString(), filterDatumOd.getText(), filterDatumDo.getText());
    }//GEN-LAST:event_jButtonFilterIzlistajRadneNalogeActionPerformed

    private void pregledRNDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledRNDetaljiActionPerformed
        if (jTableRadniNalozi.getSelectedRow() != -1) {
            pregledRadnogNalogaPoOtpremamaFrame.setVisible(true);  
            this.setVisible(false);
            this.setVisible(false);
            pregledRadnogNalogaPoOtpremamaFrame.fillData(Long.parseLong(jTableRadniNalozi.getValueAt(jTableRadniNalozi.getSelectedRow(), 1).toString()), 
                    jTableRadniNalozi.getValueAt(jTableRadniNalozi.getSelectedRow(), 2).toString(), 
                    jTableRadniNalozi.getValueAt(jTableRadniNalozi.getSelectedRow(), 3).toString(), 
                    jTableRadniNalozi.getValueAt(jTableRadniNalozi.getSelectedRow(), 4).toString(),
                    getIndexStatus(jTableRadniNalozi.getValueAt(jTableRadniNalozi.getSelectedRow(), 9).toString()));  
        }else{
            JOptionPane.showMessageDialog(this, "Niste selektovali radni nalog", "Obavestenje",0);
        }
    }//GEN-LAST:event_pregledRNDetaljiActionPerformed

    private void izvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvestajActionPerformed
        if (jTableRadniNalozi.getRowCount() >= 1) {
            pregledIzvestajaFrame.setVisible(true);  
            this.setVisible(false);
            this.setVisible(false);
            
            pregledIzvestajaFrame.getData(jTableRadniNalozi);
        }else{
            JOptionPane.showMessageDialog(this, "Popunite filtere za zeljeni izvestaj", "Obavestenje",0);
        }
    }//GEN-LAST:event_izvestajActionPerformed

    private int getIndexStatus(String status){
        int st = 3;
        if(status.equalsIgnoreCase("aktivan")){
            st = 0;
        }
        if(status.equalsIgnoreCase("zavrsen")){
            st = 1;
        }
        if(status.equalsIgnoreCase("prekinut")){
            st = 2;
        }
        if(status.equalsIgnoreCase("nedefinisan")){
            st = 3;
        }
        return st;
    }
    
    
    public void getSviRN(){
        List<db.Radninalog> result = radniNalogDb.getSviRadniNalozi();
        fillTableRN(result);
        filterFillRN(result);
        filterFillMarkaBetona(radniNalogDb.getMarkeBetona());
        filterFillKupac(radniNalogDb.getSviKupci());
        filterFillGradilista(radniNalogDb.getGradilista());
    }
    
    
    private void fillTableRN(List<db.Radninalog> result) {
        int i = 0;
        Object[][] obj = new Object[result.size()][10];
        for (db.Radninalog auto : result) {
            obj[i][0] = i + 1;
            obj[i][1] = auto.getRn();
            obj[i][2] = auto.getMarkabetona();
            obj[i][3] = auto.getKupac();
            obj[i][4] = auto.getGradiliste();
            obj[i][5] = auto.getUgovorenom3();
            obj[i][6] = auto.getIsporucenom3();
            obj[i][7] = Convert.round2Decimal(auto.getUgovorenom3() - auto.getIsporucenom3());
            obj[i][8] = Convert.convertDateToStringDate(auto.getDatum()) + " " + Convert.convertDateToStringTime(auto.getDatum());
            obj[i][9] = StatusRN.getStatus(auto.getStatus());
            //obj[i][10] = Convert.convertDateToStringTime(auto.getDatumvreme());
            i++;
        }

        jTableRadniNalozi.removeAll();
        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Radni nalog", "Marka betona", "Kupac", "Gradiliste", "Ugovoreno", "Isporuceno", "Preostalo", "Datum", "Status"});
        jTableRadniNalozi.setModel(model);
        jTableRadniNalozi.setRowMargin(4);
        jTableRadniNalozi.setRowHeight(40);
        jTableRadniNalozi.setShowGrid(true);
        jTableRadniNalozi.getColumnModel().getColumn(0).setMaxWidth(45);
        jTableRadniNalozi.setDefaultEditor(Object.class, null);

    }
    
    private void filterFillRN(List<db.Radninalog> result) {

        DefaultComboBoxModel model = (DefaultComboBoxModel) filterRadniNalog.getModel();
        // removing old data
        model.removeAllElements();
        model.addElement("");

        for (int i = 0; i < result.size(); i++) {
            model.addElement(result.get(i).getRn());
        }
        // setting model with new data
        filterRadniNalog.setModel(model);
    }
    
    private void filterFillMarkaBetona(List<String> result) {

        DefaultComboBoxModel modelmb = (DefaultComboBoxModel) filterMarkaBetona.getModel();
        // removing old data
        modelmb.removeAllElements();
        modelmb.addElement("");

        for (int i = 0; i < result.size(); i++) {
            modelmb.addElement(result.get(i));
        }

        // setting model with new data
        filterMarkaBetona.setModel(modelmb);
    }
    
    private void filterFillKupac(List<String> result) {

        DefaultComboBoxModel modelk = (DefaultComboBoxModel) filterKupac.getModel();
        // removing old data
        modelk.removeAllElements();
        modelk.addElement("");

        for (int i = 0; i < result.size(); i++) {
            modelk.addElement(result.get(i));
        }

        // setting model with new data
        filterKupac.setModel(modelk);
    }
    
    private void filterFillGradilista(List<String> result) {

        DefaultComboBoxModel modelg = (DefaultComboBoxModel) filterGradiliste.getModel();
        // removing old data
        modelg.removeAllElements();
        modelg.addElement("");

        for (int i = 0; i < result.size(); i++) {
            modelg.addElement(result.get(i));
        }
        // setting model with new data
        filterGradiliste.setModel(modelg);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker filterDatumDo;
    private com.github.lgooddatepicker.components.DatePicker filterDatumOd;
    private javax.swing.JComboBox<String> filterGradiliste;
    private javax.swing.JComboBox<String> filterKupac;
    private javax.swing.JComboBox<String> filterMarkaBetona;
    private javax.swing.JComboBox<String> filterRadniNalog;
    private javax.swing.JComboBox<String> filterStatus;
    private javax.swing.JButton izvestaj;
    private javax.swing.JButton jButtonFilterIzlistajRadneNaloge;
    private javax.swing.JButton jButtonPregledRNOdustani;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRadniNalozi;
    private javax.swing.JButton pregledRNDetalji;
    // End of variables declaration//GEN-END:variables

    private final RadniNalogService radniNalogDb;
    private final PregledOtpremaZaRadniNalogFrame pregledRadnogNalogaPoOtpremamaFrame;
    private final PregledIzvestajaFrame pregledIzvestajaFrame;
     
}
