/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import dbService.OtpremaService;
import dbService.RadniNalogService;
import dbService.SarzaService;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import print.OtpremnicaStampa;
import utils.Convert;
import utils.StatusRN;

/**
 *
 * @author branko.scekic
 */
public class PregledOtpremaZaRadniNalogFrame extends javax.swing.JFrame {

    /**
     * Creates new form PregledRadnogNalogaPoOtpremamaFrame
     * @param otpremaDb
     * @param radniNalogDb
     * @param pregledSarziZaOtpremuFrame
     */
    public PregledOtpremaZaRadniNalogFrame(OtpremaService otpremaDb,
                RadniNalogService radniNalogDb, PregledSarziZaOtpremuFrame pregledSarziZaOtpremuFrame) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.otpremaDb = otpremaDb;
        this.pregledSarziZaOtpremuFrame = pregledSarziZaOtpremuFrame;
        this.radniNalogDb = radniNalogDb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel25 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableOtprema = new javax.swing.JTable();
        jLabel70 = new javax.swing.JLabel();
        brojRadnogNalogaOtprema = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        markaBetonaOtprema = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        kupacOtprema = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        gradilisteOtprema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonPromeniStatus = new javax.swing.JButton();
        pregledOtpremePoSarzama = new javax.swing.JButton();
        jButtonPregledRNpoOtpreemamaOdustani = new javax.swing.JButton();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel69.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("Pregled otprema za radni nalog");

        jTableOtprema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "br", "vozilo", "vozac", "status", "ugovoreno", "isporuceno", "preostalo", "datum"
            }
        ));
        jTableOtprema.setFocusable(false);
        jTableOtprema.setShowVerticalLines(true);
        jTableOtprema.setSurrendersFocusOnKeystroke(true);
        jTableOtprema.setToolTipText("");
        jTableOtprema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOtpremaMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableOtprema);

        jLabel70.setText("Broj radnog naloga: ");

        brojRadnogNalogaOtprema.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        brojRadnogNalogaOtprema.setText("rn");

        jLabel74.setText("Marka betona: ");

        markaBetonaOtprema.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        markaBetonaOtprema.setText("mb");

        jLabel75.setText("Kupac");

        kupacOtprema.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        kupacOtprema.setText("k");

        jLabel112.setText("Gradiliuste:");

        gradilisteOtprema.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        gradilisteOtprema.setText("g");

        jLabel1.setText("Status");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aktivan", "zavrsen", "prekinut", "nedefinisan" }));

        jButtonPromeniStatus.setText("Promeni status");
        jButtonPromeniStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniStatusActionPerformed(evt);
            }
        });

        pregledOtpremePoSarzama.setText("Detaljno");
        pregledOtpremePoSarzama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledOtpremePoSarzamaActionPerformed(evt);
            }
        });

        jButtonPregledRNpoOtpreemamaOdustani.setText("Odustani");
        jButtonPregledRNpoOtpreemamaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledRNpoOtpreemamaOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addGap(18, 18, 18)
                                .addComponent(brojRadnogNalogaOtprema, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel74)
                                .addGap(18, 18, 18)
                                .addComponent(markaBetonaOtprema, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel75)
                                .addGap(18, 18, 18)
                                .addComponent(kupacOtprema, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel112))
                            .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(gradilisteOtprema, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPromeniStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(pregledOtpremePoSarzama, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPregledRNpoOtpreemamaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel112)
                                .addComponent(gradilisteOtprema))
                            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel75)
                                .addComponent(kupacOtprema))
                            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel74)
                                .addComponent(markaBetonaOtprema))
                            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel70)
                                .addComponent(brojRadnogNalogaOtprema)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPromeniStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregledOtpremePoSarzama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(jButtonPregledRNpoOtpreemamaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableOtpremaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOtpremaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableOtpremaMouseClicked

    private void jButtonPregledRNpoOtpreemamaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledRNpoOtpreemamaOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPregledRNpoOtpreemamaOdustaniActionPerformed

    private void pregledOtpremePoSarzamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledOtpremePoSarzamaActionPerformed
        if (jTableOtprema.getSelectedRow() != -1) {
            this.setVisible(false);
            pregledSarziZaOtpremuFrame.setVisible(true);
            pregledSarziZaOtpremuFrame.fillData(Long.parseLong(brojRadnogNalogaOtprema.getText()), 
                    otpremaDb.getOtprema(Long.parseLong(jTableOtprema.getValueAt(jTableOtprema.getSelectedRow(), 8).toString())), 
                    jTableOtprema.getValueAt(jTableOtprema.getSelectedRow(), 1).toString(), 
                    jTableOtprema.getValueAt(jTableOtprema.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_pregledOtpremePoSarzamaActionPerformed

    private void jButtonPromeniStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniStatusActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da promenite status radnom nalogu?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            radniNalogDb.setRnStatus(jComboBoxStatus.getSelectedIndex(), radniNalogDb.getRN(Long.parseLong(brojRadnogNalogaOtprema.getText())));
        }
    }//GEN-LAST:event_jButtonPromeniStatusActionPerformed

    public void fillData(long brojRadnogNaloga, String markaBetona, String kupac, String gradiliste, int status){
        brojRadnogNalogaOtprema.setText(Long.toString(brojRadnogNaloga));
        markaBetonaOtprema.setText(markaBetona);
        kupacOtprema.setText(kupac);
        gradilisteOtprema.setText(gradiliste);
        jComboBoxStatus.setSelectedIndex(status);
        fillTableOtpreme(otpremaDb.getOtpremeZaRN(brojRadnogNaloga));
    }
    
    private void fillTableOtpreme(List<db.Otprema> result) {
        int i = 0;
        Object[][] obj = new Object[result.size()][10];
        for (db.Otprema auto : result) {
            obj[i][0] = i + 1;
            obj[i][1] = auto.getVozilo();
            obj[i][2] = auto.getVozac();
            obj[i][3] = auto.getZadatom3();
            obj[i][4] = auto.getIzdatom3();
            obj[i][5] = auto.getZadatom3() - auto.getIzdatom3();
            obj[i][6] = Convert.convertDateToStringDate(auto.getDatum());
            obj[i][7] = Convert.convertDateToStringTime(auto.getDatum());
            obj[i][8] = auto.getId();

            i++;
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Vozilo", "Vozac", "Zadato", "Izdato", "Preostalo", "Datum", "Vreme", "id"});
        jTableOtprema.setModel(model);
        jTableOtprema.setRowMargin(4);
        jTableOtprema.setRowHeight(40);
        jTableOtprema.setShowGrid(true);
        jTableOtprema.getColumnModel().getColumn(0).setMaxWidth(45);
        jTableOtprema.getColumnModel().getColumn(8).setMaxWidth(5);
        jTableOtprema.setDefaultEditor(Object.class, null);

    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brojRadnogNalogaOtprema;
    private javax.swing.JLabel gradilisteOtprema;
    private javax.swing.JButton jButtonPregledRNpoOtpreemamaOdustani;
    private javax.swing.JButton jButtonPromeniStatus;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableOtprema;
    private javax.swing.JLabel kupacOtprema;
    private javax.swing.JLabel markaBetonaOtprema;
    private javax.swing.JButton pregledOtpremePoSarzama;
    // End of variables declaration//GEN-END:variables

    private final OtpremaService otpremaDb;
    private final RadniNalogService radniNalogDb;
    private final PregledSarziZaOtpremuFrame pregledSarziZaOtpremuFrame;    
    
}
