/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import dbService.VoziloService;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author branko.scekic
 */
public class VoziloFrame extends javax.swing.JFrame {

    /**
     * Creates new form VoziloFrame
     */
    public VoziloFrame(VoziloService voziloDb) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.voziloDb = voziloDb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        voziloType = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableVozila = new javax.swing.JTable();
        jButtonNovoVoziloPotvrdi = new javax.swing.JButton();
        jButtonNovoVoziloOdustani = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setResizable(false);

        jLabel110.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("Vozilo");

        jLabel111.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel111.setText("Tablice");

        jTableVozila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "br", "Tablice"
            }
        ));
        jScrollPane7.setViewportView(jTableVozila);

        jButtonNovoVoziloPotvrdi.setText("Dodaj vozilo");
        jButtonNovoVoziloPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoVoziloPotvrdiActionPerformed(evt);
            }
        });

        jButtonNovoVoziloOdustani.setText("Odustani");
        jButtonNovoVoziloOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoVoziloOdustaniActionPerformed(evt);
            }
        });

        jButton1.setText("Obrisi vozilo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(jButtonNovoVoziloPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNovoVoziloOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(voziloType, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voziloType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButtonNovoVoziloPotvrdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoVoziloOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoVoziloPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoVoziloPotvrdiActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            voziloDb.addVozilo(voziloType.getText());
            getVozila();
        }
        voziloType.setText("");
    }//GEN-LAST:event_jButtonNovoVoziloPotvrdiActionPerformed

    private void jButtonNovoVoziloOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoVoziloOdustaniActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButtonNovoVoziloOdustaniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long id = Long.parseLong(jTableVozila.getModel().getValueAt(jTableVozila.getSelectedRow(),2).toString());
        if (JOptionPane.showConfirmDialog(null, "Da li želite da obrisete vozilo ?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            voziloDb.deleteVozilo(id);
            getVozila();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTable getjTableVozila() {
        return jTableVozila;
    }

    public JTextField getVoziloType() {
        return voziloType;
    }
    
    public void getVozila(){
        updateResult(voziloDb.getVozila());
    }
    
    private void updateResult(List<db.Vozilo> result) {
        int i = 0;
        int size = 0;
        
        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAkivan()) {
                size++;
            }
        }
        
        Object[][] obj = new Object[size][3];

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAkivan()) {
                obj[i][0] = i + 1;
                obj[i][1] = result.get(j).getTablica();
                obj[i][2] = result.get(j).getId();
                i++;
            }
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Tablica", "id"});
        jTableVozila.setModel(model);
        jTableVozila.setRowMargin(4);
        jTableVozila.setRowHeight(40);
        jTableVozila.getColumnModel().getColumn(0).setMaxWidth(45);

        this.rowSorter = new TableRowSorter<>(jTableVozila.getModel());
        jTableVozila.removeColumn(jTableVozila.getColumnModel().getColumn(2));
        jTableVozila.setRowSorter(rowSorter);
        addFilter();
    }
     
      private void addFilter() {
        voziloType.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = voziloType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = voziloType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNovoVoziloOdustani;
    private javax.swing.JButton jButtonNovoVoziloPotvrdi;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableVozila;
    private javax.swing.JTextField voziloType;
    // End of variables declaration//GEN-END:variables

    private final VoziloService voziloDb;
    private TableRowSorter<TableModel> rowSorter;
}
