/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvisionNew.win;

import com.Buff;
import dbService.ZbirniParametriService;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import pogon.Pogon;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class ZbirniParametriFrame extends javax.swing.JFrame {

    /**
     * Creates new form ZbirniParametriFrame
     * @param zbirniParametriDb
     * @param pogon
     * @param mb
     */
    public ZbirniParametriFrame(ZbirniParametriService zbirniParametriDb, Pogon pogon) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        
        this.zbirniParametriDb = zbirniParametriDb;
        this.pogon = pogon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel20 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButtonParametriOdustani = new javax.swing.JButton();
        jButtonPreletiSacuvaj1 = new javax.swing.JButton();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        AOParametriVremeSmirivanjaVageFrakcije = new javax.swing.JSpinner();
        AOParametriVremePraznjenjaVageFrakcije = new javax.swing.JSpinner();
        AOParametriVremePraznjenjaKoseTrake = new javax.swing.JSpinner();
        AOParametriKontrolnoVremeKoseTrake = new javax.swing.JSpinner();
        AOParametriZadrskaNaDoziranjeVode = new javax.swing.JSpinner();
        AOParametriZadrskaNaDoziranjeCementa = new javax.swing.JSpinner();
        AOParametriVremeMesanjaMaterijala = new javax.swing.JSpinner();
        AOParametriPocetnoOtvaranjeMesalice = new javax.swing.JSpinner();
        AOParametriVremePocetnogPraznjenjaMesalice = new javax.swing.JSpinner();
        AOParametriVremeKonacnogPraznjenjaMesalice = new javax.swing.JSpinner();
        AOParametriVremeIspiranjaVageAditiva = new javax.swing.JSpinner();
        AOParametriPauzaFluidizacije = new javax.swing.JSpinner();
        AOParametriRadFluidizacije = new javax.swing.JSpinner();
        AOParametriKapacitetMesalice = new javax.swing.JSpinner();
        AOParametriZadrskaNaStartKoseTrake = new javax.swing.JSpinner();
        AOParametriVremeSmirivanjaVageAditiva = new javax.swing.JSpinner();
        AOParametriVremeSmirivanjaVageCementa = new javax.swing.JSpinner();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel86.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("Zbirni parametri");

        jButtonParametriOdustani.setText("Odustani");
        jButtonParametriOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParametriOdustaniActionPerformed(evt);
            }
        });

        jButtonPreletiSacuvaj1.setText("Sacuvaj");
        jButtonPreletiSacuvaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreletiSacuvaj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPreletiSacuvaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonParametriOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonParametriOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButtonPreletiSacuvaj1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel87.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel87.setText("- Vreme smirivanja vage frakcije (sec)");

        jLabel88.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel88.setText("- Vreme pražnjenja vage frakcije  (sec)");

        jLabel89.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel89.setText("- Vreme pražnjenja kose trake (sec)");

        jLabel90.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel90.setText("- Kontrolno vreme kose trake (sec)");

        jLabel91.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel91.setText("- Zadrška na doziranje vode (sec)");

        jLabel92.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel92.setText("- Zadrška na doziranje cementa (sec)");

        jLabel93.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel93.setText("- Vreme mešanja materijala  (sec)");

        jLabel94.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel94.setText("- Početno otvaranje mešalice  (sec)");

        jLabel95.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel95.setText("- Vreme početnog pražnjenja mešalice  (sec)");

        jLabel96.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel96.setText("- Vreme ispiranja vage aditiva (sec)");

        jLabel97.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel97.setText("- Vreme konačnog pražnjenja mešalice  (sec)");

        jLabel98.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel98.setText("- Pauza fluidizacije (sec)");

        jLabel99.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel99.setText("- Rad fluidizacije (sec)");

        jLabel100.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel100.setText("- Kapacitet mešalice (m3)");

        jLabel101.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel101.setText("- Zadrška na start kose trake (sec)");

        jLabel102.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel102.setText("- Vreme smirivanja vage aditiva (sec)");

        jLabel103.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel103.setText("- Vreme smirivanja vage cementa (sec)");

        AOParametriVremeSmirivanjaVageFrakcije.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremePraznjenjaVageFrakcije.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremePraznjenjaKoseTrake.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriKontrolnoVremeKoseTrake.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriZadrskaNaDoziranjeVode.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriZadrskaNaDoziranjeCementa.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremeMesanjaMaterijala.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriPocetnoOtvaranjeMesalice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremePocetnogPraznjenjaMesalice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremeKonacnogPraznjenjaMesalice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremeIspiranjaVageAditiva.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriPauzaFluidizacije.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriRadFluidizacije.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriKapacitetMesalice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriZadrskaNaStartKoseTrake.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremeSmirivanjaVageAditiva.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        AOParametriVremeSmirivanjaVageCementa.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 300.0d, 0.10000000149011612d));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AOParametriVremePocetnogPraznjenjaMesalice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriPocetnoOtvaranjeMesalice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremeSmirivanjaVageFrakcije, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AOParametriVremePraznjenjaVageFrakcije, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremePraznjenjaKoseTrake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriKontrolnoVremeKoseTrake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriZadrskaNaDoziranjeVode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriZadrskaNaDoziranjeCementa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremeMesanjaMaterijala, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremeKonacnogPraznjenjaMesalice))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel98, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel99, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AOParametriVremeIspiranjaVageAditiva, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AOParametriPauzaFluidizacije)
                            .addComponent(AOParametriRadFluidizacije)
                            .addComponent(AOParametriKapacitetMesalice)
                            .addComponent(AOParametriZadrskaNaStartKoseTrake)
                            .addComponent(AOParametriVremeSmirivanjaVageAditiva)
                            .addComponent(AOParametriVremeSmirivanjaVageCementa))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriVremeSmirivanjaVageFrakcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriVremePraznjenjaVageFrakcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriVremePraznjenjaKoseTrake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriKontrolnoVremeKoseTrake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AOParametriKapacitetMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriZadrskaNaDoziranjeVode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriZadrskaNaStartKoseTrake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriZadrskaNaDoziranjeCementa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriVremeSmirivanjaVageAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AOParametriVremeMesanjaMaterijala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AOParametriVremeSmirivanjaVageCementa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriPocetnoOtvaranjeMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriVremePocetnogPraznjenjaMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriVremeIspiranjaVageAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriPauzaFluidizacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriRadFluidizacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)))
                .addGap(11, 11, 11)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AOParametriVremeKonacnogPraznjenjaMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu7.setText("Rezervna kopija");

        jMenuItem7.setText("kopija");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuBar3.add(jMenu7);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        zbirniParametriDb.getZbirniParametri();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButtonParametriOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParametriOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonParametriOdustaniActionPerformed

    private void jButtonPreletiSacuvaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreletiSacuvaj1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setZbirniParametri();
            zbirniParametriDb.setZbirniParametri();
        }
    }//GEN-LAST:event_jButtonPreletiSacuvaj1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AOParametriKapacitetMesalice;
    private javax.swing.JSpinner AOParametriKontrolnoVremeKoseTrake;
    private javax.swing.JSpinner AOParametriPauzaFluidizacije;
    private javax.swing.JSpinner AOParametriPocetnoOtvaranjeMesalice;
    private javax.swing.JSpinner AOParametriRadFluidizacije;
    private javax.swing.JSpinner AOParametriVremeIspiranjaVageAditiva;
    private javax.swing.JSpinner AOParametriVremeKonacnogPraznjenjaMesalice;
    private javax.swing.JSpinner AOParametriVremeMesanjaMaterijala;
    private javax.swing.JSpinner AOParametriVremePocetnogPraznjenjaMesalice;
    private javax.swing.JSpinner AOParametriVremePraznjenjaKoseTrake;
    private javax.swing.JSpinner AOParametriVremePraznjenjaVageFrakcije;
    private javax.swing.JSpinner AOParametriVremeSmirivanjaVageAditiva;
    private javax.swing.JSpinner AOParametriVremeSmirivanjaVageCementa;
    private javax.swing.JSpinner AOParametriVremeSmirivanjaVageFrakcije;
    private javax.swing.JSpinner AOParametriZadrskaNaDoziranjeCementa;
    private javax.swing.JSpinner AOParametriZadrskaNaDoziranjeVode;
    private javax.swing.JSpinner AOParametriZadrskaNaStartKoseTrake;
    private javax.swing.JButton jButtonParametriOdustani;
    private javax.swing.JButton jButtonPreletiSacuvaj1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    // End of variables declaration//GEN-END:variables
    private final ZbirniParametriService zbirniParametriDb;
    private final Pogon pogon;
    private Buff mb;
    
    public void setMb(Buff mb){
        this.mb = mb;
    }

    
    public void setZbirniParametri() {
        int[] podaci = {Convert.objectToInt(AOParametriVremeSmirivanjaVageFrakcije.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriVremePraznjenjaVageFrakcije.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriZadrskaNaStartKoseTrake.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriVremePraznjenjaKoseTrake.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriKontrolnoVremeKoseTrake.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriZadrskaNaDoziranjeVode.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriZadrskaNaDoziranjeCementa.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(pogon.getMesalica().getVremeMesanja(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriPocetnoOtvaranjeMesalice.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriVremePocetnogPraznjenjaMesalice.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(pogon.getMesalica().getVremePraznjenja(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriVremeIspiranjaVageAditiva.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriVremeSmirivanjaVageAditiva.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriVremeSmirivanjaVageCementa.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriPauzaFluidizacije.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriRadFluidizacije.getValue(), pogon.getParametri().getBrDec()),
            Convert.objectToInt(AOParametriKapacitetMesalice.getValue(), pogon.getParametri().getBrDec())};

        mb.writeMWs(podaci, pogon.getParametri().getVremeSmirivanjaVageFrakcijeAdresa());
        
    }
    
    public void getZbirniParametri() {
        AOParametriVremeSmirivanjaVageFrakcije.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremeSmirivanjaVageFrakcije(), pogon.getParametri().getBrDec()));
        AOParametriVremePraznjenjaVageFrakcije.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremePraznjenjaVageFrakcije(), pogon.getParametri().getBrDec()));
        AOParametriVremePraznjenjaKoseTrake.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremePraznjenjaKoseTrake(), pogon.getParametri().getBrDec()));

        AOParametriKontrolnoVremeKoseTrake.setValue(Convert.shiftPointDouble(pogon.getParametri().getKontrolnoVremeKoseTrake(), pogon.getParametri().getBrDec()));
        AOParametriZadrskaNaDoziranjeVode.setValue(Convert.shiftPointDouble(pogon.getParametri().getZadrskaNaDoziranjeVode(), pogon.getParametri().getBrDec()));
        AOParametriZadrskaNaDoziranjeCementa.setValue(Convert.shiftPointDouble(pogon.getParametri().getZadrskaNaDoziranjeCementa(), pogon.getParametri().getBrDec()));

        AOParametriVremeMesanjaMaterijala.setValue(Convert.shiftPointDouble(pogon.getParametri().getZadatoVremeMesanjaMaterijala(), pogon.getParametri().getBrDec()));
        AOParametriPocetnoOtvaranjeMesalice.setValue(Convert.shiftPointDouble(pogon.getParametri().getPocetnoOtvaranjeMesalice(), pogon.getParametri().getBrDec()));
        AOParametriVremePocetnogPraznjenjaMesalice.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremePocetnogPraznjenjaMesalice(), pogon.getParametri().getBrDec()));

        AOParametriVremeKonacnogPraznjenjaMesalice.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremePraznjenjaMesalice(), pogon.getParametri().getBrDec()));
        AOParametriVremeIspiranjaVageAditiva.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremeIspiranjaVageAditiva(), pogon.getParametri().getBrDec()));
        AOParametriPauzaFluidizacije.setValue(Convert.shiftPointDouble(pogon.getParametri().getPauzaFluidizacije(), pogon.getParametri().getBrDec()));

        AOParametriRadFluidizacije.setValue(Convert.shiftPointDouble(pogon.getParametri().getRadFluidizacije(), pogon.getParametri().getBrDec()));
        AOParametriKapacitetMesalice.setValue(Convert.shiftPointDouble(pogon.getParametri().getKapacitetMesalice(), pogon.getParametri().getBrDec()));
        AOParametriZadrskaNaStartKoseTrake.setValue(Convert.shiftPointDouble(pogon.getParametri().getZadrskaNaStartKoseTrake(), pogon.getParametri().getBrDec()));

        AOParametriVremeSmirivanjaVageAditiva.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremeSmirivanjaVageAditiva(), pogon.getParametri().getBrDec()));
        AOParametriVremeSmirivanjaVageCementa.setValue(Convert.shiftPointDouble(pogon.getParametri().getVremeSmirivanjaVageCementa(), pogon.getParametri().getBrDec()));
    }

    public JSpinner getAOParametriKapacitetMesalice() {
        return AOParametriKapacitetMesalice;
    }

    public JSpinner getAOParametriKontrolnoVremeKoseTrake() {
        return AOParametriKontrolnoVremeKoseTrake;
    }

    public JSpinner getAOParametriPauzaFluidizacije() {
        return AOParametriPauzaFluidizacije;
    }

    public JSpinner getAOParametriPocetnoOtvaranjeMesalice() {
        return AOParametriPocetnoOtvaranjeMesalice;
    }

    public JSpinner getAOParametriRadFluidizacije() {
        return AOParametriRadFluidizacije;
    }

    public JSpinner getAOParametriVremeIspiranjaVageAditiva() {
        return AOParametriVremeIspiranjaVageAditiva;
    }

    public JSpinner getAOParametriVremeKonacnogPraznjenjaMesalice() {
        return AOParametriVremeKonacnogPraznjenjaMesalice;
    }

    public JSpinner getAOParametriVremeMesanjaMaterijala() {
        return AOParametriVremeMesanjaMaterijala;
    }

    public JSpinner getAOParametriVremePocetnogPraznjenjaMesalice() {
        return AOParametriVremePocetnogPraznjenjaMesalice;
    }

    public JSpinner getAOParametriVremePraznjenjaKoseTrake() {
        return AOParametriVremePraznjenjaKoseTrake;
    }

    public JSpinner getAOParametriVremePraznjenjaVageFrakcije() {
        return AOParametriVremePraznjenjaVageFrakcije;
    }

    public JSpinner getAOParametriVremeSmirivanjaVageAditiva() {
        return AOParametriVremeSmirivanjaVageAditiva;
    }

    public JSpinner getAOParametriVremeSmirivanjaVageCementa() {
        return AOParametriVremeSmirivanjaVageCementa;
    }

    public JSpinner getAOParametriVremeSmirivanjaVageFrakcije() {
        return AOParametriVremeSmirivanjaVageFrakcije;
    }

    public JSpinner getAOParametriZadrskaNaDoziranjeCementa() {
        return AOParametriZadrskaNaDoziranjeCementa;
    }

    public JSpinner getAOParametriZadrskaNaDoziranjeVode() {
        return AOParametriZadrskaNaDoziranjeVode;
    }

    public JSpinner getAOParametriZadrskaNaStartKoseTrake() {
        return AOParametriZadrskaNaStartKoseTrake;
    }
    
    
}
